### ISSUE TITLE
How to separate specials for different seasons?

### ISSUE THREAD

**Issue by cokebar** [ZeroQI/Absolute-Series-Scanner#108]
Is it to place all specials into there individual seasons, instead mixing them all together?

**Comment by cokebar** [comment]
Seems TVDB mix all seasons' specials together, but anidb is not.
So I need to rename the file according to tvdb's episode number?

**Comment by sven-7** [comment]
This is an interesting idea.  It's possible Plex could limit doing something like this.

It might be possible to do with TVDB modes (perhaps via an Agent option allowing users to select?).  While TVDB does place all specials as a season 0, they do have specials marked with an "Airs Before" or "Airs After Season".  This order can be seen here for [KonoSuba](http://thetvdb.com/?tab=seasonall&id=303867&lid=7).  It's possible things could be set up so specials are inserted between the episodes or at least within that season?  TVDB Aired Order Mode, essentially. 

@ZeroQI this would also better support a show like [Monogatari](http://thetvdb.com/?tab=seasonall&id=102261&lid=7) that we were talking about in #102

**Comment by ZeroQI** [comment]
XBMC allow special insert but not plex.

if you use Anidb numbering, a serie is just a single season so the specials linked to that very season
Tool limitation, don't see what i can do really...

**Comment by cokebar** [comment]
@ZeroQI That's a bad news for me. Renaming specials files is really a annoying work. But if I do not rename them, the scanning result is really bad if I using tvdb mode(multiple seasons).
For example:
![image 1](https://user-images.githubusercontent.com/9136591/29741917-891f50fe-8aa8-11e7-882e-115a13ea63ff.png)
I have three seasons for the anime "Hell Girl", each has one NCED file. But the result is bad, three EDs are mixed into one "Ending 1". They're recognized as files with same content. In this situation, I could only play one ED file. The other two files are unable to play in plex.

Is it possible to let the scanner think these are different files? I do not really need to put these EDs into there very season.  I just wanna they are not mixed into one.

**Comment by ZeroQI** [comment]
Please read the scanner and agent readme which states naming conventions for specials
If the read-me isn't clear please let me know how to improve it...

S2 is for 'specials no 2' using anidb convention no very bad idea to leave at the beginning of filename...
The scanner does recognise nced but you can add a number afterwards (nced2, op3, etc...)
It will remap OPs to Episodes 101-150 and EDs to Episodes 151-200

Serie/Specials/title NCED3 S03 vol8 SP.ext would be a suitable file naming scheme but since no it match no specials in thetvdb you should get no metadata for them but using the allocated specials ep range will give them a proper ep title

If you kept seasons separated using anidb numbering it would make more sense tp have metadata on your openings

**Comment by cokebar** [comment]
@ZeroQI I know I can rename three NCED files to NCED1 NCED2 NCED3 to let the scanner think they are different. But I think this is not a good solution.

1. You use NCED3 for "NCED for season 3". This is confusing. Usually, ED3 is the third Ending for a single season(maybe season1, maybe season 3).
2. For episodes renaming, I can use batch renaming tools. But for the specials, I can't. If a serie has very much seasons and each season has multiple OPs/ODs/CMs/PVs/CVTalks/etc, I have to rename these files one by one to let the metadata agent matching them correctly. This kind of renaming work is really annoying. 
If I do not rename the files, result is so bad:
![image 3](https://user-images.githubusercontent.com/9136591/29742837-e3b88796-8ab8-11e7-8275-991d13f1c114.png)

3. If the matching result is bad, do not match them to the database. So I think, adding an option which force the scanner don't give metadata to the agent for specials files, is a better solution.

**Comment by cokebar** [comment]
BTW, does Absolute-Series-Scanner has this function: "Do no scan files under specific directory"?

**Comment by ZeroQI** [comment]
Facts:
- The scanner add files into plex. (can give temporary serie name and episode titles although plex scanner does not give ep title, mine does)
- The agent give metadata to files into plex
- Even if the agent give no metadata, the episodes will still be grouped by episode number. Normally the scanner is clever to add them separately but if the text in the filename can be constructed as an anidb naming convention (nced, op, s3) it will be added incorrectly. A file in Plex at the wrong place can be read while one not showing can't...   I am not gonna impact users using anidb convention as this is the format most torrents comes as...

Options:
- if wanting the endings showing up, use these ep numbers
title s00e151 NCED S01 vol8 SP.mkv
title s00e152 NCED S02 vol9 SP.mkv
title s00e153 NCED S03 vol5 SP.mkv
- since you use tvdb numbering with openings, that's easier to put openings and endings in an "Extras" folders, and the scanner will ignore them.

**Comment by cokebar** [comment]
@ZeroQI Thanks for your advice. It helps a lot. It's very kind of you.

Plex scanner+metadata agent has many limitations. Wish plex can be better in the future so we can full custermize our library.
