### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#113]
I figure this could very well be on my end, but wanted to be sure. I've seen this happen on another show.  If I go to the XML link, it loads fine.  

```
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Forced ID file: 'tvdb3.id' with id '305074' in series folder
TVDB season mode (3) enabled, serie url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/305074/all/en.xml'
xml loading issue, Exception: '<urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>''
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by sven-7** [comment]
It also causes TVDB modes to fail.

**Comment by ZeroQI** [comment]
If link works from your pc most likely if plex server is not on same
machine then there is a firewall or ad protection blocking the url... I do
believe it is on your machine. You could use wireshark to see the request
being made and replies.
You could install another plex server for tests and see if also impacted.
Beware of firewall and add aware software that could block url loading if
'banner' is in the url for exemple

On 16 Sep 2017 16:41, "sven-7" <notifications@github.com> wrote:

It also causes TVDB modes to fail.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeroQI/Absolute-Series-Scanner/issues/113#issuecomment-329976072>,
or mute the thread

**Comment by sven-7** [comment]
The link works from the machine Plex is on.  I'll see what might be causing it, but I haven't made any major network changes.

**Comment by EndOfLine369** [comment]
@sven-7, Q: Did you do a rescan that included multiple tvdb2/3 folders? If yes, it could be the scanner is hitting 'thetvdb.com' multiple times without a long enough sleep in between.

@ZeroQI, do we do anything in HAMA for tvdb requests for frequency restraints?

**Comment by ZeroQI** [comment]
We don't, and never had the case before.... Good thinking though.

**Comment by sven-7** [comment]
@EndOfLine369 that seemed to be the case, but I think it could have been a session limitation inside the firewall. I've increased that limit, which seems to have fixed the above show after a Plex Dance.  No others were affected. 

Considered closed on my end, unless you want to use this to talk about frequency restraints we can re-open.
