### ISSUE TITLE
Special episodes won't be recognized correctly with multiple seasons

### ISSUE THREAD

**Issue by hthuong09** [ZeroQI/Absolute-Series-Scanner#123]
I have folder structure like this, for example:
```
- Toaru Majutsu no Index
    - Season 1
    - Season 2
    - Specials
        - Toaru Majutsu no Index - OP1
        - Toaru Majutsu no Index - OP2
        - Toaru Majutsu no Index - ED1
        - Toaru Majutsu no Index - ED2
        - Toaru Majutsu no Index II - OP1
        - Toaru Majutsu no Index II - OP2
        - Toaru Majutsu no Index II - ED1
        - Toaru Majutsu no Index II - ED2
```

After scanning with ASS, in Plex, show structure:
```
- Toaru Majutsu no Index
    - Season 1
    - Season 2
    - Specials
        - Opening 1
        - Opening 2
        - Ending 1
        - Ending 2
```
It will only recognized 4 files. Other files were treated as duplicate.
Anyways to correct this except separate each season into series?

**Comment by ZeroQI** [comment]
They have the same numbering so they get assigned to the same episode number.
i think opening 1 in 2 versions is a very clean result, one per season, it does allow to view all...

You do not follow anidb numbering since you put specials of 2 series together
you do not follow tvdb numbering since they don't add openings and endings to specials...
https://www.thetvdb.com/?tab=season&seriesid=83322&seasonid=35909&lid=7

If you really cared about specials you would use anidb numbering and splitting seasons
Otherwise put them in an "Extras" folder and they won't be listed

I really don't see how opening and endings are important to stream BUT let me know if my scanner and agent was super clever, what episode number should it assign to the duplicates ? i could make it multi seasons op/ed are listed sequentially but you would have to name them ep 3 and op 4 but should i support people not following any naming conventions? it is hard to keep all working tvdb modes already in the code, many possibilities...

just call them op 3 and 4 ed 3 and 4 but meta will be wrong or absent

**Comment by hthuong09** [comment]
> i think opening 1 in 2 versions is a very clean result, one per season, it does allow to view all...

I didn't know about this. Just checked it out, doesn't very helpful because it shows bit rate and resolution as options, so I wouldn't know which is which

>  really don't see how opening and endings are important to stream BUT let me know if my scanner and agent was super clever, what episode number should it assign to the duplicates ? i could make it multi seasons op/ed are listed sequentially but you would have to name them ep 3 and op 4 but should i support people not following any naming conventions? it is hard to keep all working tvdb modes already in the code, many possibilities...

Naming it ep 3 or 4 would feel so wrong. Just wonder, OP, ED also have name, why don't you use that name instead of Ending 1, Opening 1?

You are right, OP, ED are not that important, I just want to know if there is a way to name it probably. If there is not, it's still fine.

**Comment by ZeroQI** [comment]
1 episode can only have 1 title....
Using meta name for openings? Are you even using the beta branch? it should have it since while...
S1 and s2 are sor specials. i will not impact people using proper numbering and following either anidb or tvdb convention for people that don't...
I would have put them in an "Extras" folder to skip them...

**Comment by GlassedSilver** [comment]
> Can't think of a way to allow anidb specials for multiple seasons in a single series and see when tvdb specials convention isn't used instead...

Mind if I chime in? Because I know a naming convention.

OPs and EDs and all other similar events where you wanna group various seasons of one show that anidb insists are different shows (*eyeroll* different topic) have episode IDs.

https://anidb.net/perl-bin/animedb.pl?show=ep&eid=117734 would be a nice example.

This is the first OP for K-On!! (K-On!'s second season).

This is unique to this one particular OP or anything else for that matter.

Because let's face it: some may not mind putting every season into a separate show folder in Plex, but it really doesn't look clean when you scroll through your library and have animes with vastly different amounts of seasons and it also makes "On Deck" cumbersome. There's some other drawbacks that obviously those who use this system don't mind, but as with all sorts of organization what looks tidy and sorted to one person can look like a misorganized mess to somebody else.

As for how important it is to stream OPs or EDs I don't quite get this question.

It's not important to stream them, but having all associated media ready to go within Plex and neatly sorted is quite nice and having the agent pull the correct meta data for what we DO have information for would be cool as well.

I understand you closed this issue, but I want to kindly ask to reconsider this decision.

**Comment by ZeroQI** [comment]
You can
- use anidb2 to have seasons as separate series on disk but grouped in Plex in a single series so it does not make "On Deck" cumbersome and should have metadata on correstly names openings (s00e101+)
- Label them s00e103-104 for OPs and s00e153-154 for EDs as per readme > no metadata
- Place them in "Extras" folder so they are not detected by the scanner.
- use grouping folder + collection display in library settings
-anidb3/4 

ANY other ecosystem for meta force anidb or tvdb numbering, not concurrently.
You didn't went enough in depth to see the implications, and avoided the numbering and conflicting with tvdb numbering potential issues and which ep number to give, If you tell me not to change the ep number, that would raise the complexity in the agent code for people genuinely following a documented tvdb naming convention when I can barely maintain the agent code as we speak...

Your option is not realistic.
- You do not get to choose tvdb numbering on disk and plex to have specials using anidb naming convention...
- Did you try anidb2 mode? That would show as tvdb/single series in plex while being anidb numbered on disk. I could correct meta in agent if op/ed not showing meta in Hama...

**Comment by GlassedSilver** [comment]
Hmm, if I use anidb2 would OP1 for Season 1 and OP1 for Season 2 not collide within Plex or would the different names of the “episodes” incentivize Plex to keep them as separate entries and not do the whole “I have two formats of this episode” thing that had been pointed out earlier.

I’m sorry if I come across as someone who is unwilling to rtfm, but I’m currently in the process of deploying my unRAID server and you have no idea how many tabs I have open with help threads, guides and all that kind of stuff because I’m finally getting around to bringing some structure and order into my files - media and beyond. So that also means a lot of new applications and the possibilities.

I invested a lot of time reading the guides for HAMA and ASS, but maybe I misunderstood the one paragraph that solves it all or I’m being too cautious.

Anyhow thank you so much for creating these tools, without them Plex would be almost worthless for animes. (:

**Comment by ZeroQI** [comment]
The scanner gives season and ep number. if the id assigned by the agent is the same, then they will be 2 formats of the same ep... Doesn't aniDB2 mode move op/edsas 501+ eps though?
- Openings are a difficult point. I would put them in "Extras" folder so plex ignore them OR  use AniDB numbering. There is no middle ground. If you care about opening metadata, use strict AniDB numbering but do not tell me opening meta is more important than specials or episodes...
- other specials present in thetvdb would be remapped with anidb2 mode

I crossed anidb to tvdb and made multiple way to display data different from on disk to avoid renumbering massively episodes (renaming series folder at best) and not present in any metadata oriented player to date (Kodi, emby).

Again rename the specials folder Extras and plex will be pristine and devoid of them.
