### ISSUE TITLE
Certificate Failing

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Absolute-Series-Scanner#136]
The Scanner just started giving the following error and my serie tagged with anidb2 aren't scanning into tvdb like they should. Not sure if the two are related.

```
Forced ID in serie folder name
Creating: /tmp/anime-list-corrections.xml
Error downloading ScudLee's file mod from local/GitHub 'http://rawgit.com/Dingmatt/AMSA/master/Plug-in%20Support/Data/com.plexapp.agents.amsa/DataItems/anime-list-corrections.xml', Exception: '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>'
Creating: /tmp/ASS-tmp-anime-list-master.xml
Error parsing ScudLee's file mod content, Exception: '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>'
```

**Comment by dgw** [comment]
Should be using `https://cdn.rawgit.com`, for one. It appears (from a quick test) that HTTP redirects to HTTPS at rawgit, but the certificate appears valid to me.

**Comment by deusxanime** [comment]
@mweber03 I have the same issue that started yesterday, or at least I first noticed it then. I posted in the [Plex forums ASS thread](https://forums.plex.tv/discussion/113967/absolute-series-scanner-for-anime-mainly/p32) (latest couple posts you can see mine and @ZeroQI's answer). Sounds like he isn't aware yet, but good to see I'm not the only one, so this will get it more exposure. Not sure what the issue is. I've restarted my container/Plex. I can wget that URL no problem from within the container, but not sure if the urlopen() python works differently. I tried changing the "http://" to "https://" in the URLs of the .py file, but no luck there either. 

It is very strange as I haven't updated my HAMA/ASS on there in months so not sure what would have changed. All I can think is something external such as the way git is handling it or something with python?

**Comment by dgw** [comment]
Something that could have changed is the certificate store, or lack thereof, during a package update. Perhaps https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error will be helpful for troubleshooting?

**Comment by deusxanime** [comment]
@mweber03 What are using ASS/HAMA on? Just wondering if it is due to an update we might both have gotten recently. I use linuxserver.io's Plex docker container on unRAID where this is happening. I can't remember exactly when it last updated, but they usually have one around once a week, on or near the weekends.

**Comment by mweber03** [comment]
I'm just running Plex on a Synology server.

**Comment by ZeroQI** [comment]
Using on synology too.
Try beta branch scanner. Uses different URL...

**Comment by deusxanime** [comment]
Tried changing to the new URL, but same error (just with the new URL instead):

```
Creating: /tmp/anime-list-corrections.xml
Error downloading ScudLee's file mod from local/GitHub 'http://rawgit.com/ZeroQI/Absolute-Series-Scanner/master/anime-list-corrections.xml', Exception: '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify f
ailed (_ssl.c:590)>'
Creating: /tmp/ASS-tmp-anime-list-master.xml
Error parsing ScudLee's file mod content, Exception: '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>'
```

**Comment by mweber03** [comment]
Seems to not be an issue in the Beta

**Comment by deusxanime** [comment]
@mweber03 So you switched to this one?

https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/Beta/Scanners/Series/Absolute%20Series%20Scanner.py

**Comment by mweber03** [comment]
I did some more investigating and I think this is still a problem. And I believe it is a problem in the beta, but the beta just doesn't have the same verbosity of its logs.

**Comment by mweber03** [comment]
Here is the reason why:

[RawGit will become HTTPS-only on February 17, 2018](https://rawgit.com/news/https-only)

**Comment by dgw** [comment]
HTTP URLs redirect to HTTPS though. Why would that in itself cause a certificate issue? Only if the certificate won't verify on the system running this scanner.

RawGit switching to https-only is only revealing an issue with SSL verification.

**Comment by mweber03** [comment]
I don't disagree that this revealed a latent issue, my point was really that this is why it appeared suddenly.

I do have a fix to test out when I have a spare moment.

**Comment by mweber03** [comment]
The fix seems to work, I'll be making a pull request shortly.

**Comment by deusxanime** [comment]
@mweber03 Awesome that you found it. Does that fix it for both the legacy and beta scanners? Something simple you can give a quick rundown here?

**Comment by mweber03** [comment]
Pull requests are out:
master - https://github.com/ZeroQI/Absolute-Series-Scanner/pull/138
beta - https://github.com/ZeroQI/Absolute-Series-Scanner/pull/139

I haven't gotten to test the beta yet though if someone wants to give it a shot. Otherwise, I'll be testing it out later this evening.

**Comment by ZeroQI** [comment]
Thanks a lot, i would not have been able to solve quickly...

**Comment by mweber03** [comment]
No problem, both master and beta seem to be working swimmingly now.

**Comment by deusxanime** [comment]
@mweber03 @ZeroQI Fix worked great on master branch. On my main Plex server, I was able to Plex Dance the series that had been added since the change to https on git and they scanned in right now and combined into single tvdb entry.

Something isn't working right now on the beta branch for me now though. I tried to Plex Dance and in the step where I move it out of the directory and rescan, none of the series went away. Everything seemed to be stuck in there. Couldn't figure it out so I just deleted the library (this is small directory on my testing Plex server, so nbd) and recreated it. Now it just isn't seeming to see any of the files/folders. The library is just empty. Any chances here or since that may cause this?
