### ISSUE TITLE
One Piece issues

### ISSUE THREAD

**Issue by saitoh183** [ZeroQI/Absolute-Series-Scanner#143]
Hi, 

first off im not using the latest version of the scanner because the version i have been using has always worked well.

Now When i first added One Pieces using tvdb2, it had added as season folders and was just how i wanted it. Then after a certain episode everything was rescan for some reason and placed under 1 episode

```
folder_show: 'One Piece [tvdb2-81797]', folder_season: 'None', tvdb mode: '2', tvdb id: '81797'
TVDB season mode (2) enabled, serie url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/81797/all/en.xml'
different abs number found on ep (s18e1) after starting to manually place our own abs numbers. all episodes will be added as season 1.
```
Since then i cant get it back

what do i need to do to fix it?

**Comment by sven-7** [comment]
This is because someone mistakenly put an episode out of order.  Usually look for the season it started messing up and you'll find something.  [Here it is.](https://www.thetvdb.com/?tab=episode&seriesid=81797&seasonid=671098&id=6504809&lid=7)

[I've requested it be removed](https://forums.thetvdb.com/viewtopic.php?f=7&t=45477), which will fix One Piece when you get new metadata next.

**Comment by saitoh183** [comment]
Thanks . I had just found that as well after reading this https://forums.plex.tv/discussion/comment/1365099/#Comment_1365099
