### ISSUE TITLE
hama crashed

### ISSUE THREAD

**Issue by yeelok** [ZeroQI/Absolute-Series-Scanner#155]
Hama crashed on loading metadata for anime with anidb id 10585 (THE IDOLM@STER CINDERELLA GIRLS)

All EPs were recognized as expected by the scanner but failed to load the metadata.

hama log file:
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2032372/com.plexapp.agents.hama.log)

Folder Logs:
[THE IDOLM@STER CINDERELLA GIRLS.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2032380/THE.IDOLM.STER.CINDERELLA.GIRLS.filelist.log)
[THE IDOLM@STER CINDERELLA GIRLS.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2032381/THE.IDOLM.STER.CINDERELLA.GIRLS.scanner.log)

**Comment by ZeroQI** [comment]
@yeelok Thanks for attaching logs straight away. The metadata update fails because the agent crash, due to an error in TheTVDB xml files: http://thetvdb.com/api/A27AD9BE0DA63333/series/289763/all/ja.xml
If you open it by clicking on it, you can see it clearly. I did solve this some time ago in beta branch 

your hama log show xml files for TheTVDB, and if you found no other logs with the filelist you are using old master agent branch'

Please have a look at my logs using your file naming:
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2032544/com.plexapp.agents.hama.log)
You will see the work done between your version and beta one. Please update to Hama beta branch (https://github.com/ZeroQI/Hama.bundle/tree/Beta-Agent) and feedback any issue onegaishimasu

**Comment by yeelok** [comment]
@ZeroQI Thanks. The beta branch works perfectly.

**Comment by ZeroQI** [comment]
Glad it works for you. While not perfect, the beta branch has quite some code and hours that went into it and am glad it works perfectly for you
