### ISSUE TITLE
UTF-8 files break the scanner when comparing videoId tokens

### ISSUE THREAD

**Issue by cricalix** [ZeroQI/Absolute-Series-Scanner#164]
If filenames (from Youtube in this case) contain letters that are not contained in the ASCII character set, line 641 of the current ASS.py breaks with an error about being unable to decode byte 0xc3.

On my Synology, running Python 2.7.12, changing line 641 to read
`
if video['snippet']['resourceId']['videoId'] in file.decode('utf-8'):`

resolves the error.

A filename containing Creme Brulee spelt with the appropriate accent grave etc should demonstrate the problem adequately.

Can't do a PR right now, because the Synology isn't set up for doing it.

**Comment by ZeroQI** [comment]
@cricalix Thanks for that, i would have searched a while for the error...
You are in Ireland too? Never seen a summer like that in years here. That said, after the bleeding blizzard we got this winter, can't really complain...

Any comment for youtube support?
- scanner adds playlist best
- scanner adds channels per file date since youtube-dl update file modification date, using year as seasons, and ep number incrementially from the oldest

Working on better posters but tricky...

**Comment by cricalix** [comment]
Yes, grand weather, long evenings are nice. Now, if the weather will just hold for at least a few weeks...

I'm currently trying to grok why my 82 MKV item folder of Binging with Babish is showing up as 32 items after processing by either ASS or the Youtube bundle. I suspect my fix for one issue might have caused another one, but a Synology is not a great place to try and edit code...

This line:

"Binging with Babish [youtube-PLopY4n17t8RCHa_5dR6d5GuL0YKbBxDpA]" s01e001                         "__" "Binging with Babish: Michael Scott's Pretzel from The Office" "Binging with Babish - Season 1 -
 S1E51 - Binging with Babish - Michael Scott's Pretzel from The Office - [NHA9Ffaal2M].mkv"

makes me suspicious, because file 51 shouldn't be mapping to episode 1.

**Comment by cricalix** [comment]
Hmm, nope, it's not that decode fix. Odd. Something for later in the week I think, when my brain isn't broken from a day of debugging production code.

**Comment by ZeroQI** [comment]
Tell me about it, doing network switch support reading logs all day...
The thing is youtube flag some videos as episodes but cannot get seasons or episodes numbers from youtube
I could extract them from the title but would have false positives since most youtube videos don't have them so for channels i start sequentially, but fro playlist shouldn't be an issue

working on scanner, issues with playlist loading and order

**Comment by ZeroQI** [comment]
Please test, this should resolve few playlist and channel issues

**Comment by cricalix** [comment]
Yep, 246acf0 is good, a whole bunch of episodes just showed up on a re-scan.

**Comment by ZeroQI** [comment]
The only drawback is series folders without channel or playlist tags will show up as s00e501+ but i think that is acceptable for now at least it is showing. closing that bug report for now
Thanks for reporting, the scanner is much better now
