### ISSUE TITLE
scanner is picking up resource forks besides video files

### ISSUE THREAD

**Issue by jordirodo** [ZeroQI/Absolute-Series-Scanner#168]
In OSX, resource fork files might exist for some video files. They have the same filename as the video but starts with `._`

ie:
video: One Piece - 835.mkv
fork: ._Once Piece - 835.mkv

Those fork files should be ignored.
Probably adding `'.DS_Store', '^\._'` in `IGNORE_FILES_RX` should avoid that.

(Not sure if there's any anime name that starts with that though.

**Comment by ZeroQI** [comment]
Files were picked up because of the video extension so added '^\._' to IGNORE_FILES_RX.
Don't see a need for .DS_Store which is not picked up by extension
Anime: Niea_7, .Hack are the on;y to come to minf so none to date with both, and regex is only for filenames so we are grand.
Please test and close if resolved or report otherwise. Ganbanwa!

**Comment by jordirodo** [comment]
Works perfectly. Thanks @ZeroQI !
