### ISSUE TITLE
Another method of parsing and custom word filter

### ISSUE THREAD

**Issue by Akior** [ZeroQI/Absolute-Series-Scanner#170]
Hello.

It's a possible to add an additional scan method? 
Example: 
add to plex a dir /home/
inside dir:
/home/Naruto/Season 1/1.mkv ... 100.mkv
/home/Bleach/Season 1/1.mkv ... 100.mkv
/home/Season 2/Naruto/1.mkv ... 100.mkv
/home/Season 2/Bleach/1.mkv ... 100.mkv

So I mean that ../Season 2/Naruto/1-100.mkv will be added in plex as "Season 2" . **Now it added as "Season 1"**

WHACK_PRE_CLEAN is a first clean of folder name ? 
/home/Naruto x264-FMD Release/1.mkv will parse as Naruto or /home/Naruto [x264-FMD Release]/1.mkv will be Naruto ? Can I add a custom word for this massive ?

**Comment by ZeroQI** [comment]
WHACK_PRE_CLEAN is a set of full strings sometimes with spaces that gets removed, for which removing words individually is not possible as they could be part of the episode or serie title, like 'Release' so removing 'x264-FMD Release' make sense.
Here it is in square brackets so it will be removed

Technically it's possible but i would advise against it since i no longer can see clearly if a series use AniDB numbering or TheTVDB numbering by checking the number of seasons, of if a grouping folder let through a single series so let it pass through normally instead of adding it through the root folder call....

I must ask why somebody would purposely  choose this seriously weird naming convention that no other software will support if i am not wrong?

**Comment by Akior** [comment]
Ru dub is worst.
Look at files:
/home/Overlord III AniLibria.TV HDTV-RIP/Overlord III [01] [AniLibria.TV] [HDTV-RIP].mkv
There are nothing about season number.

I wrote an automatic downloader from site, It download files with folder name as season number -
/home/season 3/Overlord III......

So if you can write a parser with this function, this will be great!

**Comment by ZeroQI** [comment]
You do not need season number if it is a single season series (AniDB numbering)
Episode number (and everything in brackets) are ignored. That is a super bad naming convention

Improvements to the scanner possible:
- include in regex ep numer 2-3 digits in square brackets IF a release group put the ep number in brackets like "[01]". Please ocnfirm
- WHACK_PRE_CLEAN need added for the folder part (anything sure not to cause issue with genuine titles): "AniLibria.TV" and "HDTV-RIP"

You have to modify your script to swap season and series: /home/Overlord III../season 3/....
Can you show me your script, i am pretty sure it can be modified to that effect, and am interested in it...

**Comment by Akior** [comment]
I make a construction:
Overlord / Season 1/1 -- 10.mkv
Overlord / Season 3/Overlord III AniLibria.TV HDTV-RIP/Overlord III [01] [AniLibria.TV] [HDTV-RIP].mkv
It works perfect. 
WHACK_PRE_CLEAN for AniLibria.TV and other words works great! 
Thank you.

**Comment by ZeroQI** [comment]
Adding in scanner code "AniLibria.TV" and "HDTV-RIP".
Are you sure the episode number is in squared brackets (in 'Overlord III [01] [AniLibria.TV] [HDTV-RIP].mkv') ?
"Overlord / Season 3/Overlord III [01] [AniLibria.TV] [HDTV-RIP].mkv" should work without "Overlord III AniLibria.TV HDTV-RIP"
