### ISSUE TITLE
episodeoffset="-1" fails but both episodeoffset="1" works

### ISSUE THREAD

**Issue by Feredzhanov** [ZeroQI/Absolute-Series-Scanner#207]
So I had an odd mapping problem and I'm not sure if the problem is with ASS interpreting wrong ScudLee's offset values, or if the same problem exists with Kodi (last I remember ScudLee's list is generally made for use with Kodi plug-ins).

So the original list mapping is:
```
<anime anidbid="12498" tvdbid="254653" defaulttvdbseason="4" episodeoffset="-1" tmdbid="" imdbid="">
    <name>High School DxD Hero</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-18;</mapping>
    </mapping-list>
  </anime>
```
But then AniDB Ep. 02 is mapped as TVDB Ep. 02 no matter how I change the value.
However, this:
```
  <anime anidbid="12498" tvdbid="254653" defaulttvdbseason="4" episodeoffset="" tmdbid="" imdbid="">
    <name>High School DxD Hero</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-18;</mapping>
      <mapping anidbseason="1" tvdbseason="4" start="2" end="13" offset="-1"/>
    </mapping-list>
  </anime>
```
works as intended.
I'm not sure if it's a bug in ASS or not, just may be worth checking though, since it's almost sure to happen somewhere else as well.

**Comment by ZeroQI** [comment]
I am sorry but you are not making any sense to me
- i do not see the file naming
- i do not see what the scanner detect is as episode and if detected at right season/scanner in Plex
- only anidb 2-4 modes would change the season and numbering using Scudlee file, which i don't know if you are even using that, so are you sure it is not an agent issue?

I need
- What is your filename and path.
- To which season and episode does it get mapped to.
- custom scanner logs as per readme
- "AniDB Ep. 02 is mapped as TVDB Ep. 02 no matter how I change the value.". How do you know that? i see no longs to confirm or disprove this statement.

**Comment by Feredzhanov** [comment]
Ok, so here are the logs with the first settings (the one currently in ScudLee's list
[High School DxD Hero [anidb2-12498].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058724/High.School.DxD.Hero.anidb2-12498.agent-search.log)
[High School DxD Hero [anidb2-12498].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058725/High.School.DxD.Hero.anidb2-12498.filelist.log)
[High School DxD Hero [anidb2-12498].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058726/High.School.DxD.Hero.anidb2-12498.scanner.log)

And here are after the changes:
[High School DxD Hero [anidb2-12498].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058738/High.School.DxD.Hero.anidb2-12498.agent-search.log)
[High School DxD Hero [anidb2-12498].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058739/High.School.DxD.Hero.anidb2-12498.filelist.log)
[High School DxD Hero [anidb2-12498].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058740/High.School.DxD.Hero.anidb2-12498.scanner.log)

**Comment by Feredzhanov** [comment]
Ok, so apparently, negative values don't work in the current scenario.
[High School DxD Hero [anidb2-12498].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3058780/High.School.DxD.Hero.anidb2-12498.scanner.log)

**Comment by ZeroQI** [comment]
episodeoffset="-1" fails but both episodeoffset="1" and mapping offset "-1" works
- Orig: s01e001 => s00e018
- Orig: s01e002 =>  s04e002, should be s04e001 if mapping works as it should...
- This is a confirmed bug with negative offsets for "episodeoffset".

High School DxD Hero [anidb2-12498].scanner.log was sufficient to see the failed mapping, here is my approach to see where was the issue. I now see what you meant...
- no error in anidbTvdbMapping() since it pinted: anidb: '12498', tvbdid: '254653', name: 'High School DxD Hero', mappingList: {'s1e1': 's0e18', 'defaulttvdbseason': '4', 'episodeoffset': '-1'} so 
- add_episode_into_plex seem to not interpret the negative eppisodeoffset
- isdigit() does not like negative numbers!!!! never knew...
- need a new test function to test if a string is an integer:

def isinteger(string):  
  return isdigit(string) or len(string)>1 and string.startswith("-") and string[1:].isdigit()
or much simpler but not a one liner:
    try:                          return int(string)
    except ValueError:  return False

I cannot put into the master for now as i cannot test but if anybody can:
- add the new function
- replace all isdigit() calls for offset with isinteger() lines 375 and 714

**Comment by EndOfLine369** [comment]
Could even just use:
```python
IS_INT=com(r"^-?\d+$")
def isinteger(string):  return bool(IS_INT.search(a))
```

**Comment by ZeroQI** [comment]
@EndOfLine369 why using regex when you don't have to? i honestly cannot tell what the function does reading the code,,,

Please test and report

**Comment by EndOfLine369** [comment]
Was just to give another option 😃

**Comment by ZeroQI** [comment]
The option is good but in an obscure way. I am super bad with regex...

I prefer the shortest code but readable. I know i do it my way otherwise
wouldn't have bpther coding as much. It's becoming harder.
Btw, If you need me to prioritise something let ne know what as i can't
focus much.
I tried reducing the number of bug reports but they keep increasing...

**Comment by ZeroQI** [comment]
So... is the fix (or the scanner still) working?

**Comment by sven-7** [comment]
I think this broke anidb4.  Nothing I'm adding is working with it now. 

See logs on current master:  
[Bungo Stray Dogs.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3099539/Bungo.Stray.Dogs.filelist.log)
[Bungo Stray Dogs.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3099540/Bungo.Stray.Dogs.scanner.log)

See logs on commit  d30b789 - where it is working:

[Bungo Stray Dogs.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3099541/Bungo.Stray.Dogs.scanner.log)
[Bungo Stray Dogs.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3099542/Bungo.Stray.Dogs.filelist.log)

**Comment by ZeroQI** [comment]
Look like it was crashing, isdigit() method works on strings but not as standalone function...
Just submitted to fix https://github.com/ZeroQI/Absolute-Series-Scanner/commit/a7ef39014104c92e433b33e0fa114097fcd48a55
Please test and report

**Comment by sven-7** [comment]
Seems good to me now.

**Comment by ZeroQI** [comment]
Excellent :D
Thanks for testing
