### ISSUE TITLE
Unified Anime Folders?  AKA:  GUIDs Anywhere

### ISSUE THREAD

**Issue by wwkimball** [ZeroQI/Absolute-Series-Scanner#219]
I'm sorry that I'm struggling with your scanner.  I am trying to add Anime to Plex in the most sensible way.  My requirements are:

1. All assets of a single franchise are presented by Plex as a single logical entity.  This includes TV Shows and Movies together **on one page** within the UI.  This also includes all Seasons of the same TV Show, even when those Seasons go by different names.  So, a page for "Ghost in the Shell" shows all the various TV Shows and Movies together.  Also, even though the Seasons for "Ah My Buddha" have different names, they are both still just "Ah My Buddha" and thus, appear together as different Seasons under a single page for the "Ah My Buddha" franchise.
2. The play order within Plex honors the story sequence, **threading TV Shows and Movies in chronological story order**.  So, pressing Play on "InuYasha" will thread the various Movies in between episodes of the TV Show as befits the story.
3. The metadata respects the order presented by physical media box-sets, thus not forcing me to re-sequence episodes to fit any conflicting order shown by web-sites like TvDB.com.  When I import a box-set, **that box-set is the authority on the episode order**, not any website.  To help with this, I meticulously:
   1. add the name of every episode to the file-name of every episode file, so I expect any Plex scanner to honor the episode **names** I add myself and similarly, present the episodes in box-set order via Plex, *not* web-site (TvDB) order; and
   2. split apart any multi-episode files into separate episode files, meticulously naming each with its now-singular episode name.

These requirements are reasonable, evidenced by Google showing many other people with exactly the same needs.

So, can your Absolute-Series-Scanner help with this?  I truly hope so.  I will present some of my pain points with it, so far.  If you already have viable solutions for these issues, I'd love to learn them; I have so far been unable to deduce these techniques from your documentation.  I've read and re-read the docs over and over because the instructions are confusing.

At this point, I have deleted TvDB from all Absolute-Series-Scanner configurations because literally every sequencing error comes from TvDB.  AniDB has the correct episode orders but seems to present different Seasons as entirely different Series.  So, neither is perfect.  I need a Scanner like yours to bridge this very frustrating gap between what I have on physical media and my desire for Plex to show it as-is **without any monkeying-around**.  I **do not** want to:
1. rename all of my thousands of files just to fit TvDB's idiotic ordering, or
2. hop manually from "TV > Series S > Season T > Episode N" to "TV > Series S > Specials > Episode J" to "Movies > Movie M" and back to "TV > Series S > Season T+1 > Episode 1" just to watch the story unfold in proper chronological order!

The best of all worlds would be a means of linking **every** asset by its "GUID" (as you call it), **not** just the top-level Series directory.  For example, let us do this:

```
# Note that this example presents the `anidb` IDs at the **Season** level.  This is necessary
# because -- despite the additional sub-title on Season 2, it is still just more "Ah My Buddha".
/volume1/
/volume1/Plex/
/volume1/Plex/anime/
/volume1/Plex/anime/Ah My Buddha/
/volume1/Plex/anime/Ah My Buddha/Season 1 [anidb-3168]/
/volume1/Plex/anime/Ah My Buddha/Season 1 [anidb-3168]/ep1 - Don't Get Me Aroused!!.mkv
/volume1/Plex/anime/Ah My Buddha/Season 1 [anidb-3168]/ep13 - Don't Rest!! [anidb-46235].mkv
...
/volume1/Plex/anime/Ah My Buddha/Season 2 [anidb-4145]/
/volume1/Plex/anime/Ah My Buddha/Season 2 [anidb-4145]/ep1 - Don't Tempt Me!!.mkv
/volume1/Plex/anime/Ah My Buddha/Season 2 [anidb-4145]/ep13 - Don't Be Fooled!! [anidb-51715].mkv

# When a GUID is present, it must suffice as enough information to go pull the Metadata.  This
# must be true whether the GUID is on a directory- or file-name.
...
```

The pain-point without this "GUIDs Anywhere" capability is that "Ah My Buddha" is presently broken apart in the Plex UI into two distinct Series:  "Ah My Buddha" and "Ah My Buddha (2006)".  I don't want that.  I'm unable to get both "Ah My Buddha" Series entries to combine into just one "Ah My Buddha" Series with two Seasons, as it should be.

Next, extend the example above to include Movies with TV Shows.  Continue to support "GUIDs Anywhere" so that the Movies can be presented at the Franchise (Series) level, like so:

```
/volume1/Plex/anime/Ghost in the Shell/Movies/Ghost in the Shell (1995) [anidb-61].mkv
/volume1/Plex/anime/Ghost in the Shell/Season 1 - Stand Alone Complex [anidb-247]/ep1 - Section 9.mkv
...
/volume1/Plex/anime/Ghost in the Shell/Season 2 - Stand Alone Complex, 2nd Gig [anidb-1176]/ep1 - Reembody.mkv
...
/volume1/Plex/anime/Ghost in the Shell/Season 2 - Stand Alone Complex, 2nd Gig [anidb-1176]/ep26 - Endless Gig.mkv
/volume1/Plex/anime/Ghost in the Shell/Season 2 - Stand Alone Complex, 2nd Gig [anidb-1176]/ep27 - Ghost in the Shell - Stand Alone Complex - Solid State Society (2006) [anidb-4414].mkv

# Here's the magic trick:  ep27 is a "fake" episode.  It's actually the Movie that ends Season 2.
# But make it show up in Plex as if it were the next Episode!  The GUID at the end of the
# file-name must be enough information for your scanner to handle the Metadata.
```

Without this "GUIDs Anywhere" capability, I can't figure out how to blend the Movies and TV Shows together under a single "Ghost in the Shell" Series, nor such that the Movies will logically play at the point during the overall story where they best fit.  Instead, they're all broken apart into different Series based on the different Movie names and Season names.  It's endlessly frustrating.

The logic has to be simple enough.  When the file-name starts with "ep", and has a GUID like [anidb-#####], then you'll pull Metadata from https://anidb.net/perl-bin/animedb.pl?show=ep&eid=##### or its API equivalent.  When there's no "ep" prefix on the file-name, pull from https://anidb.net/perl-bin/animedb.pl?show=anime&aid=##### or its API equivalent.  Note the difference between `eid` and `aid`.

Or, are you already doing this and I just couldn't parse that from the documentation?

**Comment by ZeroQI** [comment]
Hey i googled and find many people wanting to earn money without working, therefore it is reasonable... Your argument is a fallacy but some or your expectations can be met.

1 - Plex can use collections to group items together and hide items in collections so they are shown once only
2 - anidb3 mode can help puting series and movies in order but there is no play order in plex i can manipulate so the numbering has to be altered to play in order... tvdb5 mode manage that for a single 
tvdbid so you need to use XBMC>Kodi for that functionality 
You are using grouping folders as the 
3 - there is a tvdb dvd order if you use tvdb agent and edit settings... or use tvdb5 chronological order using tvdb absolute numbering index for eps
3i - then find a scanner doing that (mine does) but choose an agent not refreshing metadata

Select Plex Library settings to
- show collections
- do not show items in collections
- do not show single seasons folder

Set hama collection setting to 'Local' and it will use the grouping folder as collection entry so if you have it as you wish 

Use my scanner to load movies in series library... As described in the readme...

> One library for both movies and TV series
> Movie files in Series libraries (since this is a Series Scanner) are supported if:
> 
> Files are in a folder with the same name or with a single file inside it
> Filename contain " - Complete Movie"
> Files are numbered (01|ep 01|s01e01)

You cannot have this numbering work with my scanner: 
- Ghost in the Shell/Movies/Ghost in the Shell (1995) [anidb-61].mkv

Also forced id on files doesn't work on files... Use:
- Ghost in the Shell/Ghost in the Shell (1995) [anidb-61]/Ghost in the Shell (1995).mkv

If you had not put an anidbid on the season folder for "Ah My Buddha" it would have been detected with 2 seasons...

**Comment by wwkimball** [comment]
You've said a lot, but I still don't follow.  Yes, I've read your documentation; still don't get it.  You speak in too many "do this *or* do this *or* do this *or* do this".  That's seriously confusing.  I put in the effort to very clearly articulate the outcome expectations.  What **one** path do I follow in order to get **that** outcome?  If some of my requirements are impossible, then please clearly indicate which part(s) is/are impossible.  However, if it's possible to meet all of the requirements but **not at the same time**, please clearly indicate which requirements are in conflict and what can be done to "enable requirement N but not requirement M".

I don't understand these statements:
1. "Hey i googled and find many people wanting to earn money without working, therefore it is reasonable":  I gave you a clear message that helping me with this issue would help a lot of **other** people with the **same questions/requirements**.  It's a nudge to you to answer here but also consider updating your README because **I won't be the only person looking for the same answer**.  Please provide further information with that larger audience in mind; you aren't answering solely for my benefit.
2. "anidb3 mode can help puting series and movies in order"; "can help"?  Does it or does it not accomplish the goal?
3. "so the numbering has to be altered to play in order": In what way does the numbering have to be altered?  By me -- changing file-names?  changing Plex preferences?  changing your scanner settings? -- or by the scanner by changing the GUID type from anidb to tbdb5?  However, any time you bring up TvDB, I'm going to remind you that I clearly said I don't use TvDB (because it messes up Episode ordering).
4. "so you need to use XBMC>Kodi":  I have no idea what this means.  I'm using Plex, not XBMC.  Are you suggesting I move all of my Anime to XBMC?  Please explain how a user would accomplish what you mean to suggest.
5. "then find a scanner doing that (mine does) but choose an agent not refreshing metadata":  What?  You seem to say both "use my scanner" and "don't use my scanner" in this same sentence.  Which is it?  Or do you mean "don't use the Plex agent"?  If so, what other agent should I use that's available on iOS, OSX, Windows, XBox One, PS4, and new Samsung TVs (my family uses Plex on **all** of these)?
6. "Set hama collection setting to 'Local'":  Just to confirm, are you instructing me to change `Prefs[collections            ] = Local, AniDB, TheMovieDb` to just `Prefs[collections            ] = Local`?
7. "If using tvdb numbering on disk or anidb and using anidb2 mode will use anidb numbering on files but displaying using tvdb nummbering":  What?  Would you please demonstrate this with a detailed example directory structure with at least two compliant file names?
8. I read your README, repeatedly.  I experimented with different ways to apply your README.  It's just not clear at the section you quoted; I couldn't get anything I tried to work.  It's the crux of why I opened this issue.  I realize your README probably makes all the sense in the world to you, but I can't understand it.  Would you please use the example directory structure and file-names that I provided, and fix them so that they'll work with your scanner such that the requirements in the original post are met?
9.  (almost(?) an answer to 8, but confusing):  **"You cannot have this numbering work with my scanner"** (fair enough), but then **"Use: ..."** (I see you're using a Grouping directory for all of Ghost in the Shell.  I didn't use that because your README indicates Grouping directories cause repeat scanning.  Is this not actually the case or not really a problem?  Please clarify this.), and then **"Or use anidb3 to have seasons as per anidb chronological order for the series/movies"** (What?  Too many "or".  Which path is the solution?)
10. "If you had not put an anidbid on the season folder for "Ah My Buddha" it would have been detected with 2 seasons":  This is not true.  I tried **exactly** that.  I ended up with two different Series, separately named "Ah My Buddha" and "Ah My Budda (2006)", instead of one Series with two Seasons.  Here's what I actually have:

```
/volume1/entertainment/anime/Ah My Buddha [anidb-3168]/{ep,s}{1..12} - Episode Title.mkv
/volume1/entertainment/anime/Ah My Buddha [anidb-4145]/{ep,s}{1..12} - Episode Title.mkv
```

This produces two separate Anime franchises in the Plex index, as I've stated.

Please help.  Your code is probably amazing, if I could just understand how to use it to affect the stated requirements.

**Comment by wwkimball** [comment]
Follow-Up:

I just tried the following:
1. Move all of my Anime to a new directory.
2. Pick a small sample size of franchises and copied them back to the old Library directory.
3. Delete all GUID tags from the directory names, removing all `[anidb-#####]`.
4. Push all content one directory layer deeper so that the top level directory is Collection, then Season-or-Complete-Movie-Name, then the MKV files at the deeper directory level.
5. Destroyed the old Anime Library in Plex, Rebuilt the DB, flushed all Bundles
6. Recreated the Anime Library.  I set the Collections preference to "Hide items which are in collections".  I set the Seasons preference to "Hide for single-season series".  I set the Scanner preference to "Absolute Series Scanner".  I set the Agent to "HamaTV".  I set the HamaTV Settings `collections` preference to only `Local`.  I deleted every reference to TvDB in the HamaTV Settings (every single one of them).
7. I waited for the new Anime library to build.

The result is not good.  In several of the sample Anime franchises, the first Episode and the first Special (OVA, or whatever) are now combined into one Episode.  This makes no sense as I very carefully followed the "epNN" or "sNN" file-name prefix for every single file.  In some cases -- like "Ah My Buddha" -- the first Special of every Season that isn't 1 is now missing.  They are on the file-system, but no longer in Plex.

Removing the `[anidb-NNNN]` GUID appears to have made the situation worse.

**Comment by ZeroQI** [comment]
1 - Specials are season 0. You can't put specials in a season folder like "anime/Air Gear/Season 1/s1 - OVA Name.mkv" will be put in s01e01, so you will have two s0xe01. Working as designed
2 - weird but you are not meant to put specials into season folder, that doesn't follow Plex numbering rules [https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/]
3 - issues on code for json (and xml) <64 bytes, might be that, difficult to say without logs, have no time to reproduce as i have major bug in hama and littlew time to correct already
4 - do the plex dance, Plex doesn't rescan if the folder content didn't change, that make testing the scanner horrible as you need to keep moving files around to re-scan.... Hama relies on TVDB heavilly so if you add anime with one season only it will use AniDB numbering, 

 "GUIDs Anywhere" => big NO. Plex associate an id to a series, that id is used for metadata. If you spend time putting ids in files, then follow a numbering exactly (anidb or tvdb, as scanner and agent support both mixed in same library but not the sane series obviously)

Issues
- You have season folders which is only supported by tvdb numbering but follow neither tvdb numbering nor anidb numbering. 
- I didn't write anidb3 part. it uses anidb chronology to set a season per series/movies and is the closest to your playlist order requirement that cannot be done as you cannot insert a special in the middle of a season (tvdb5 could do that but you don't want tvdb numbering but use seasons which is tvdb numbering since anidb numbering)
- DVD order is a library setting not supported by metadata sources generally but you can use tvdb agent (not Hama) to do that: https://forums.plex.tv/t/
pulling-dvd-order-vs-aired-order-from-thetvdb/207054. There isn't many series with ordering issues, everybody renames to match anidb or tvdb numbering or use tvdb agent for that one series with tvdb numbering, my agent doesn't support dvd order
- Kodi support putting specials in between episodes when playing https://forum.kodi.tv/showthread.php?tid=281014
- "what other agent should I use that's available" > tvdb agent needs tvdb numbering. anidb agent not usable and myanimelist not sure it works and hama most useable one in the lot.,. ASS is the only scanner allowing movies in series library and hama the only one to display metadata for movies in series library... Any other system separate movies and series in different libraries...
- " your README indicates Grouping directories cause repeat scanning" > where is it written?
- you do not want to rename all files but want to write an id to all files... Make up your mind...
- dual season is tvdb numbering so you cannot both deny tvdb and want multiple season
- doubt tvdb messes up the dvd numbering for "ah my buddah" or does it?
 
Start with test library and use
- Plex since you have to (Kodi doesn't support streaming) + ass (since it allows movies in series library) + hama (support movies in series library)
- Plex library settings to display collections, hide items in collection, hide season folder if single ones
- Hama setting Prefs[collections ] = Local so only grouping folders give collections. Use only grouping folders with more than one item inside preferably (there may be a bug with single folder inside them, had no time to test)
- if series mismatched then use correct anidb title or forced id [anidb-xxxxx]. You don't have to use forced ids on all folders
- agent and scanner assume anidb numbering unless 2 or more seasons present
- since you do not want to even display using tvdb numbering, anidb 2 and tvdb modes are out of the picture so use anidb numbering for everything. That means one series per season (displayed potentially out of order but season folder hidden for single season series so you won't see the difference in the interface)

Use the following To group items together
- Collection > Series title > series title xx.ext (using anidb or tvdb numbering. no specials in a season folder)
- Collection > Movie title (year) > Movie title (year).ext

Or the following without grouping
- Series title > series title xx.ext (using anidb or tvdb numbering(with tvdb id if single season or mismatched). no specials in a season folder)
Movie title (year) > Movie title (year).ext (force anidb id if mismatched)

**Comment by wwkimball** [comment]
Thank you for taking time out of your day to pursue this!  I'm hopeful that by the end, we'll have produced a straight-forward step-by-step guide for other Anime fans who regularly face these same challenges.

1. I understand this.  I use this Plex numbering scheme successfully in my non-Anime libraries.  I was under the impression that ASS/Hama override the Plex numbering scheme and so I'm trying to find the "sweet spot" between Plex numbering versus TvDB numbering versus AniDB numbering such that Anime Series and Movies are sensibly grouped, ideally with Specials sequenced in story-chronological order (if possible).

2. I only added the /Season N/ directories because I understood that was one of your earlier suggestions.  I can certainly take them back out because I'm working with a small test set of Series.  However, doing so begs this question:  How do I then correctly represent on the file-system that AniDB has different pages for different Seasons of some shows.  For example:
* "Ah My Buddha" has two Seasons, per AniDB, represented as two distinct pages; without GUIDs Anywhere (or at least at the Season level), I don't know how to correctly present this to ASS/Hama:
   * Season 1:  https://anidb.net/perl-bin/animedb.pl?show=anime&aid=3168
   * Season 2:  https://anidb.net/perl-bin/animedb.pl?show=anime&aid=4145
* These aren't two different Series.  It's all just "Ah My Buddha", so it makes sense to have both of these together in Plex under one Series name.  I don't care whether all the Episodes are dumped together -- but sequentially -- or in separate Seasons; I just don't want a distinct Series entry for every Season of every Series.  The resulting Library is untenably large due to how many Seasons of all of the Series I have.
* Both Seasons include one OVA (i.e.:  Special) episode, each.
* Before I moved all the files into Seasons directories for this most recent experiment, ASS/Hama was perfectly happy to have all the ep* and s* files in each "Series-as-Season" directories, excepting that it was automatically moving the OVA Episodes into a Specials entry in the UI (I'd really rather the OVAs simply stay within the Seasons from which they come, if possible).  I was okay with this outcome except that each Season of each Series was appearing in the Library as a distinct Series.
* Please correct me here:  In order to match up the Metadata, it seems like I am required to number the Episodes according to how they appear on the linked AniDB pages; from ep1 to ep12 plus s1 for both Season 1 and Season 2.  Here's where ASS/Hama causes some frustration because if I use Season directories to keep the ep1-ep12+s1 files apart, the code suddenly switches to TvDB mode.  Because AniDB doesn't have one page for *all* Episodes of this Series, how else should I group these files on the file-system so that ASS/Hama know how to pull the Metadata from AniDB instead of TvDB while keeping both Seasons under a single Series?
* **Yes, TvDB does *improperly* order the "Ah My Buddha" episodes**.  For example, TvDB mistakes Season 1, Episode 12 as Season 1, Episode 1 and repeats it again as Episode 12 under a slightly different -- but wrong -- Episode title, entirely omitting Episode 1 (which is nonsense because the "real" Episode 1 introduces all the characters whereas Episode 12 is a much later adventure wherein the characters clearly already have history together and the viewer is expected to understand back-references).  Because of errors like this, and other discrepancies between TvDB Episode ordering versus box-set ordering, I simply don't trust TvDB for Anime.  AniDB gets it right in every case I've tested where TvDB got it wrong.
* Other Anime Series have the same issue; different Seasons have their own pages on AniDB, so any working solution you have for "Ah My Buddha" should translate to the rest.

3. I'm quite happy to help troubleshoot further.  I appreciate that your time is constrained; I too am an Open Source author (click my GitHub avatar for just some examples) on top of having a regular day-job, so I fully understand that you can only address this here-and-there.  Just let me know what I can gather for you and I'll fetch it.  This sub-issue can wait; solving the greater challenge of meeting the original requirements stated for this issue is paramount.

4. I did the Plex dance, resulting in the same outcome as described in my earlier post.  This is likely because I've stripped the test files down to just a dozen Series and some only have a Movie in them, like "./Ah My Goddess/Ah My Goddess - Complete Move (2006)/Ah My Goddess - Complete Move (2006).mkv".  I'll add more files to the test set to see if this clears up.

**"Plex associate an id to a series, that id is used for metadata"**
I'd seen that Plex associates Metadata to the Series tier but was hopeful that ASS/Hama were clever enough -- as plug-ins -- to extend that to the Season or even Episode level.  As far as I'm concerned, we're ultimately talking about writing Metadata to records in a NoSQL database.  As long as the schema is known, this would be trivial code.  My thinking was that clever enough plug-ins could probably set the Metadata for **any** element at the DB layer, resolving Plex's own deficit in this respect.  When I saw that ASS/Hama could use a different external data provider at the Series level, I was delighted and was hopeful that your code either was already -- or could become -- clever enough to also solve this Plex design shortcoming.  I gather from your "big NO" that my idea of GUIDs Anywhere is something I should investigate on my own time and that's fair.

**"Issues"** (Responses)
* As stated above, I only added the Seasons directories in response to your earlier post as an experiment.  I can certainly take them back out since I'm working this issue with a very small sub-set of my overall Anime collection.
* *Understood*:  "Special" episodes like OVAs cannot be injected into automatic play order but I can get Series and Movies to thread chronologically if I switch to anidb3 or tvdb5; question:  do I just add [anidb3] or [tvdb5] tags to the Series directory names to activate these modes, or must I include the asset IDs, like [anidb3-#####] every time I want to employ this automatic threading mechanism?  Otherwise, we'll have to look into manually-defined Playlists as an alternative.  *Not understood*:  "which is tvdb numbering since anidb numbering"; this feels like an incomplete thought; since anidb numbering... what?  Please elaborate.
* From the link, it seems the DVD ordering mechanism based on TvDB data is fragile and not well supported.  I'm looking to ASS/Hama with its AniDB support as a stable solution.
* Repeat scanning reference in the README under "Grouping folder" at https://github.com/ZeroQI/Absolute-Series-Scanner#grouping-folder:  **"it will work but be scanned every time"**.  This reads as a caution against using Grouping folders.  Was it not meant as such?
* As for renaming the files, let me explain:  I've already meticulously named countless files using "epNN - Episode Title.mkv" format, following the order they appear in the box-sets from which they came.  I'm unwilling to rename these files *just to change the order of them* solely to fit with an on-line data source like TvDB, especially considering AniDB ordering matches perfectly with what I have.  I am willing to add ID tags to any file-names where the Episode orders are in conflict with on-line data sources so that Plex can receive the correct Metadata for affected episodes.  I would certainly not need to add such a tag to every file, but rather only those files for which on-line data sources have conflicting data.  This should be rare -- if ever -- as long as the on-line data source is AniDB and not TvDB.
* "dual season":  again, I only added the Seasons directory level to the test files in order to experiment based on your earlier post.  However, without some sub-directory level, the question above (coping with AniDB having different pages for each Season of a Series) comes into play.
* As illustrated above with regard to "Ah My Buddha", TvDB in fact does mess up Episode listings and ordering; I don't feel TvDB is trustworthy.  AniDB is far superior in this respect.

I feel like we're close to a solution.

**Comment by ZeroQI** [comment]
Rules
- Do not call a folder "season" without meaning it in tvdb way. it will not read specials inside, will forced tvdb mode if season 2+. That is your main mistake
- if two anidb series (don't call them seasons as it is confusing even if appropriate as we cannot differentiate with tvdb seasons then...) have specials, use anidb numbering (or rename using tvdb numbering)
- DVD numbering should be converted to anidb or tvdb numbering, no but...
- either create an entry as per anidb page with no season folder OR one entry as per thetvdb page. This is the base and if you want to do neither you are on your own. It is tricky enough when labelled correctly with all modes
- don't put "complete movie in the folder name", just name them the same like: /Ah My Goddess/Ah My Goddess (2006)/Ah My Goddess (2006).mkv
- i did it id everywhere for youtube agent if you want to check. detected series are assigned an id that is reused in update functions. Same id and series are grouped so tricky. i use in in anidb2 mode to translate to a tvdb id with right season and ep numbers and two separate anidb series are grouped as if you named them like thetvdb perfectly BUT you need perfect numbering. DVD order match neither anidb nor tvdb. if you really care you put them back in the real tv order. yes that's a pain, a rare pain... Somew things like star wars i mentionned in the readme, use tvdb5 and it use chronological order to put them straight...
- must include the asset IDs, like [anidb3-#####] every time to employ this automatic threading mechanism

Relative path to Plex library root for simplicity

AniDB numbering+collection:
- Ah My Buddha\Ah My Buddha!!\ep1-12.ext +s1.ext 
- Ah My Buddha\Ah My Buddha!! (2006)\ep1-12.ext+s1.ext
- Ah My Goddess/Ah My Goddess (2006)/Ah My Goddess (2006).mkv

It will create a collection "Ah My Buddha" with two series:
- Ah My Buddha!!
- Ah My Buddha!! (2006)

AniDB numbering showing as tvdb numbering:
- Ah My Buddha!! [anidb2-3168]\ep1-12.ext +s1.ext 
- Ah My Buddha!! (2006) [anidb2-4145]\ep1-12.ext+s1.ext

TVDB numbering:
- Ah My Buddha!!\Specials\s00e01 don't rest.ext 
- Ah My Buddha!!\Specials\s00e02 don't be fooled.ext 
- Ah My Buddha!!\Season 1\ep 1-12.ext 
- Ah My Buddha!!\Season 2\ep1-12.ext

1- I painfully added grouping folders and movie support and changed regex. it was laborious but still tied to plex for the rest
2-do not make the 'season' named folder the series folder that's weird and specials in it, it won't like...

"These aren't two different Series." Yes they are two separate series in AniDB that each have their own entries that represent two seasons/series of the same show. Semantic is paramount here...

"it will work but be scanned every time". This reads as a caution against using Grouping folders. Was it not meant as such? => Yes because plex scan once, with series folder at the library root and only rescan when the folder changes. If you put all in grouping folders, it scan it everytime and can take up to 3/4 hours to scan but some users abused it... Had plex database corruption during development and it's a hack. If you put a single series in it, i may have a bug remaining.

tvdb2 take absolute numbering and put tvdb seasons and reset the ep number each season
tvdb3 take absolute numbering and put tvdb seasons and keep the absolute number episode, that's more for long running series
tvdb4 use season for sagas. you can select your own seasons but i have a bug as it doesn't get metadata passed the original first season. Doesn't work with other entries like separate movies, specials listed in thetvdb with absolute ep number it will. You cannot insert spare movie as you want and should be content to have a collection with tvdb numbered series to have the least entries with the most seasons showing...

Looked and numbering is the same between anidb and thetvdb. Please expand:
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=3168
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=4145
https://www.thetvdb.com/series/ah-my-buddha/seasons/all

**Comment by wwkimball** [comment]
I'll try the rest of your ideas a bit later -- have to head out for awhile -- but between here and there, an answer for your query:

"Looked and numbering is the same between anidb and thetvdb. Please expand:"  The Metadata for Season 1 Episode 1 is wrong at TvDB.  "Don't Awaken!!" is Season 1 Episode 12 (the ghost haunting episode).

**Comment by ZeroQI** [comment]
It's echi still (watched it)
Issues comes from thetvdb being a tv database so if it aired in the same order no issue...
The summary was correct as is the episode number, they couldn't air the first episode in any other order , clearly the episode name was wrong, so i updated thetvdb since the series wasn't locked...

**Comment by wwkimball** [comment]
***"so i updated thetvdb since the series wasn't locked"***
I must say, you've really taken the impetus out of my distrust for TvDB with that news.  I didn't consider the bad TvDB data as being mutable.  You initially weakened my stance against TvDB with the revelation that the Firefly episode order could be corrected with that news-to-me DVD Ordering option several replies ago (this has long been an unrelated pain-point for me).  When I saw AniDB had good data, I assumed the only path forward was to permanently switch from TvDB to AniDB.  You have soundly demonstrated that I was wrong.

I spent time last evening thinking about this entire issue thread in light of what you've shown me about TvDB being more flexible than I'd known.  In retrospect, I've wasted your time with my anti-TvDB attitude.  For that, I'm sorry.

I would like to pursue the option of threading Anime movies into the series at the correct story-chronological points.  My understanding of how to precisely accomplish this is weak.

I've read your posts above a few times trying to sort that mechanism out.  I understand from your writing that OVAs won't be threaded (despite it being obvious that OVAs should play as the last "virtual episode(s)" of the disc(s) from which they come); that is unfortunate but still better than nothing.  So to the point, in order to have the movies thread in at the right story point, are we required to:
1. use Grouping Folders (i.e. Franchise Name) to collect movies with shows;
2. add a [*something*] tag to the Grouping Folder for every Anime that has movies and shows;
3. place each movie into its own dedicated sub-directories, like ./Franchise Group/Movie (YEAR)/Movie (YEAR).ext;
4. separate the episodes into "Season N" sub-directories to fit TvDB numbering; **and**
5. move all OVAs (and any other non-primary content) into a Season 0 directory?

What **exactly** is the [*something*] tag?  You offered multiple options, so I can't tell which **one** is the best fit.  Please correct anything else I may have mistaken.

And again, I truly appreciate you taking time out of your day to help!

**Comment by ZeroQI** [comment]
Let's summarize rules and reasons

Movie and series together mean a Plex collection tag to group them

The grouping folder and hama collection setting set to "Local" will fill the collection label in series and movies automatically, no need for any id in the grouping folder. 

Movies in a same name folder

I would optionally add to series folder name in front [0x] to set them in the right chronological viewing order on disk but will be scrubed out.  Everything in square brackets is ignored

Put specials in 'Season 0'  or 'Specials' folder as per thetvdb numbering if you used seasons. 
If thetvdb doesn't have it as special use any db numbering with it on its own series folder. 

The Grouping folder is meant to work but have a bug for now, So no grouping folder with single series folder inside.

**Comment by ZeroQI** [comment]
With this settings,  how is your library faring?

**Comment by wwkimball** [comment]
In order to test threading between movies and shows, I decided to fix an old problem in my library as part of this effort:  Bleach is a mess.  It was one of the earliest I imported and ... it's not healthy.  So, I'll need probably a week to sort it out because some episodes are combined into single files, most don't have Kon's Illustrated Guide to Soul Reapers properly threaded, and I don't even remember at which points the various movies are supposed to thread in.  Worse of all, the episodes don't have title screens, so it's very difficult to tell whether they're even in the correct order without a partial watch-through here-and-there.

Please bear with me while I contend with this nightmare.

**Comment by ZeroQI** [comment]
use an anidb client enabled renaming tool that use checksums for identifying them?

**Comment by wwkimball** [comment]
Sorry for the delay; that was a *lot* of work.  I have split/joined, grouped, and renamed all the "Bleach" episodes so they perfectly match TheTVDB.com's listing.  I have also included two of the movies with the sample data set.  After several arrangements and "Plex Dance" routines, I have the following results:

1. Your hint that the "Grouping Folders" are actually automatic "Collection Tags" represented as grouping directories was extremely helpful.  With that specificity, I was able to understand that the movies and shows under them need to be grouped as if they were at the top level of their respective Plex directories (movie/show), like:

```
./anime/  # Top-level directory of an Anime collection
./anime/Bleach/  # This is the Collection Tag name for everything that will go into it; this name is arbitrary
./anime/Bleach/Bleach/  # This is for the TV show
./anime/Bleach/Bleach/Season N/  # Each Season per TheTVDB.com goes here
./anime/Bleach/Bleach/Season N/epMM.mkv  # Each eposide is named according to TheTVDB.com numbering
./anime/Bleach/Bleach - The Movie - Memories of Nobody (2006)/  # A sub-directory for each movie
./anime/Bleach/Bleach - The Movie - Memories of Nobody (2006)/Bleach - The Movie - Memories of Nobody (2006).mkv  # An actual movie file, named exactly as the directory containing it
./anime/Bleach/Bleach - The Movie 2 - The Diamond Dust Rebellion (2007)/  # Another movie sub-directory
./anime/Bleach/Bleach - The Movie 2 - The Diamond Dust Rebellion (2007)/Bleach - The Movie 2 - The Diamond Dust Rebellion (2007).mkv  # Another movie, named exactly the same as its directory
```

2. When it comes to episode file naming, you do not actually need to use `Bleach - s##e##.ext` form because `ep##` works perfectly well.  So, `./Bleach/Bleach/Season 01/Bleach - s01e11.mkv` is identical to `./Bleach/Bleach/Season 01/ep11.mkv`

3. This **works** to automatically *collect the TV Show with its movies*.  The top level of the Library shows one card for Bleach with "3 shows".  Clicking into it shows separate cards for the TV Show and one each for the movies.

4. This **does not work** to *sequence the movies at the right points between TV Show episodes*.

Granted, there is debate as to where the Bleach movies *should* fit since they are non-canon.  So, I added another TV Show + Movie (+ OVA) combination to the test that suffers no such ambiguity:  "Ah!  My Goddess".

Grouped exactly as I had with Bleach, this set doesn't work as well.  I haven't yet sorted out why not, even after performing another Plex Dance.  For some reason, the Movie for "Ah!  My Goddess" is presented at the top level of the Library, along-side the collection it is to be contained within.  The Bleach set doesn't have this issue, so the discrepancy is curious.  That said, the Movie does appear in two places:  at the Library top level as its own card, and within the automatically-generated "Ah My Goddess" Collection.  Both point to exactly the same file.

The chronological order of "Ah!  My Goddess" is well-known:
1. OVA
2. The Movie
3. The 3 TV Shows

However, the movie doesn't thread between the OVA and the first TV Show season.

Am I missing something?

**Comment by ZeroQI** [comment]
Check in libraries settings if the items in collections are hidden. 
If so,  then two entries are matched to the same metadata

**Comment by wwkimball** [comment]
Anime Library settings:
*  [x] Include in dashboard
* Episode sorting:  Library default
* [x] Enable video preview thumbnails
* Collections:  Hide items which are in collections
* Seasons:  Hide for single-season series
* Scanner:  Absolute Series Scanner
* Agent:  HamaTV
* HavaTV Settings:  all default

In the same Library, the Bleach movies (2 of them) properly appear only within the Bleach collection.  The "Ah!  My Goddess" movie appears in two places.  Odd that one franchise would be treated differently from another.

EDIT:
So, I added a new franchise to expand the test and the "Ah! My Goddess" movie was suddenly absorbed into the "Ah My Goddess" collection after the card for the new franchise popped up.  Let's chalk this up as a possible defect in the Plex desktop client?

Back to the second topic:  How do we get the movies to play between TV show seasons in proper story-chronological order?  There are other franchises where this will be important.

Thanks!

**Comment by ZeroQI** [comment]
Plex do not have such playlist systems. One could add [01] [02] in froont of titles to sort them alphabetically but a text file with viewing order might be better

The only system coming close is anidb3 (movies at end of seasons) and 4 (movies a new seasons) modes but i didn't code it into the scanner nor played with it yet
