### ISSUE TITLE
Scanner Failing On Numbered Episode Names

### ISSUE THREAD

**Issue by ItsCinnabar** [ZeroQI/Absolute-Series-Scanner#225]
Neverland uses names like this "121045" for its episodes. I don't know why they do this but hey oh well.  My naming scheme is as follows "The.Promised.Neverland-S01E01-121045-HDTV-1080p.mkv". This works for every other show I've added, but on neverland I end up getting 264 episodes. I assume it's seeing the 121045 or other episode names like it and trying to read that in as a season/episode?

I would like to keep episode names in the filename, is there a way I should edit the naming scheme? Or is this an issue on ASS side?

**Comment by purposelycryptic** [comment]
If you're set in using *period-for-space* substitution in your filenaming scheme, either for legacy compatibility, or simply because of personal preference, you should be able to avoid this issue by going with `The.Promised.Neverland-S01E01.-.121045-HDTV-1080p.mkv`.

Many naming schemes use `sXXeYY-ZZ`  to indicate multi-episode files containing the range of episodes from YY to ZZ,, so separating that intent in usage from this case with an all-digit episode name would be difficult for an algorithm to determine; most platforms (Plex, Kodi, Emby, etc) recommend either the 
`SERIES_NAME - sXXeYY - EPISODE_NAME [NON-AGENT_DATA_01] [NON-AGENT_DATA_02].EXT`
or
`SERIES_NAME - XeYY - EPISODE_NAME [NON-AGENT_DATA_01] [NON-AGENT_DATA_02].EXT`
or the Absolute Numbering
`SERIES_NAME - YY - EPISODE_NAME [NON-AGENT_DATA_01] [NON-AGENT_DATA_02].EXT`
formats to avoid that issue, with XX or X being the season number, and YY the zero-padded episode number, and optionally including the first airing year in round brackets after the SERIES_NAME.

Your naming scheme is similar, using periods in place of spaces, except it omits any form of spacing around the hyphens, leading to this issue; in order to keep as close to your original scheme as possible, while avoiding this and other potential issues, I would recommend something like this:

 `The.Promised.Neverland.-.S01E01.-.121045.[HDTV-1080p].mkv`.

That way you avoid issues caused by lack of spacing, both at the series and episode name, and the video format and source are isolated in square-brackets, meaning they will be completely ignored by the scanner, completely removing them as a potential error source. Just my $0.02.

**Comment by ZeroQI** [comment]
unique tit;es with only numbers could cause issues
Just remove the hyphen, tags like hdtv and 1080 should be in square brackets
- "The Promised Neverland S01E01 [121045] [HDTV] [1080p].mkv"

**Comment by ItsCinnabar** [comment]
Ok, I will happily update my format your suggestions then. I only went with this because it was default sonarr having a .-. and I just removed the extra . cause it looked weird. 

Thank you!

**Comment by ItsCinnabar** [comment]
Works perfectly, scanned in at 12 episodes.
