### ISSUE TITLE
Other ways of handling OVAs

### ISSUE THREAD

**Issue by jvmunhoz** [ZeroQI/Absolute-Series-Scanner#232]
Anime new seasons 99% of the times receive a different name from the earlier seasons (excluding 2 cours anime, which I usually consider to be a single season), so each season would appear as a different tile in Plex. Since that happens, I'd like to put the OVAs inside the folder of the specific season it relates to.

But that's currently not possible. The only way to isolate the OVAs inside the anime folder is to put them inside the **Specials** folder, but no metadata is retrieved if there aren't any actual specials or they mess up the metadata if there are.

The solution would be to allow for a deeper search inside the folder structure for everything that's not labeled as **TV Series** if there already are any **TV Series** on a higher folder hierarchy. The folder which the OVAs are located would need to be named as they are in AniDB (or with the AniDB ID), not inside a folder simply named OVAs like is the case with the Specials.

But it's the last step that I'm not sure. Is it even possible to create an OVAs folder to put the files and metada? I've only ever seen **Specials** or **Season XX** inside Plex. I have some ideas in case of multiple OVAs, but that can be discussed later on.

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------

I will try to illustrate what I meant to make it more clear.

The anime is **Akagami no Shirayuki-hime**, and the folder is organized like [this](https://i.imgur.com/GCSq4GY.png) , with the [episodes ](https://anidb.net/anime/11082)not inside any folder and the [OVA](https://anidb.net/anime/11524) inside an OVA folder with the proper AniDB ID.

The expected result would be an [**Akagami no Shirayuki-hime** tile](https://i.imgur.com/bXAvffN.png), with the [Season 1 folder along with an OVAs folder which would contain the OVA](https://i.imgur.com/s4rutqg.png) **with the proper metadata**.

Would something like this even be possible?

**Comment by ZeroQI** [comment]
Pick a numbering convention, either AniDB or TheTVDB and stick to it. You seem like a TheTVDB king of guy so either you use anidb2 mode to display AniDB series and movies using TheTVDB numbering or rename all to TheTVDB numbering. If you name the movie/OAD the same as the folder it will be picked as a series so both can coexist

You don't answer the question of which season and episode should be assigned to the naming convention you invented...I cannot make Plex support something not a season and not a special...
Ask Plex through a feature request, but the answer will probably be no. No agent nor scanner support that all platforms included Tomy knowledge.

Kodi ex XBMC allow to insert specials in between episodes, might be more suited for you but agents are strict AniDB numbering...

**Comment by purposelycryptic** [comment]
> Anime new seasons 99% of the times receive a different name from the earlier seasons (excluding 2 cours anime, which I usually consider to be a single season), so each season would appear as a different tile in Plex. Since that happens, I'd like to put the OVAs inside the folder of the specific season it relates to.

Your issue stems from confusing the concepts of *seasons* and *series*; anime, as it is produced in Japan, does not use the concept of *seasons* -instead, what you consider a season is considered a new *series* in the franchise. Each series has its own specials (or not) that are associated with it. 

OVAs are generally categorized as their own independent entry in the franchise, even when they only have a single episode, as they are produced separately, and are not associated directly with a specific series.

To use your example, the **Akagami no Shirayuki-hime** franchise currently consists of three series/entries:
 - **Akagami no Shirayuki-hime** - 1-cour series
 - **Akagami no Shirayuki-hime: Nandemonai Takaramono, Kono Page** - 1-episode OVA
 - **Akagami no Shirayuki-hime (2016)** - 1-cour series

While, in terms of plot chronology, the events in the OVA occur between the two series, the OVA was bundled with the limited edition of the 15th volume of the manga, and did not air in TV, nor was it bundled with either series collection; it was a separate production project, essentially a bonus for dedicated readers of the manga, with the expectation that the majority of viewers of the TV anime would likely never get to see it (production and distribution for these is generally fairly limited). Thanks to the miracle of piracy, it has been fairly well digitally distributed in the West, but that is not the norm in its country of origin, or among the audience it was created for.

Hence if you intend to use the Japanese organizational model for your anime, it will never be associated with a specific series in a franchise, but rather stand on its own among them.

If you would like to have OVAs in a *specials* folder, and organize your anime using the Western *seasons* concept, you should instead use the Western/TVDB organizational standard (TVDB's organization often uses its own arbitrary system, but is as close to an official Western standard as we have for metadata).

But it is impossible to have a metadata agent follow an organizational system based entirely on your own personal preference or interpretation of associations, as there is no metadata source that uses such a structure. The closest you might get is Shoko, the new iteration of which has been under development for over a year now, as it identifies episodes by their file hashes, and so, theoretically, could support any file organization scheme, but the current version is still very much a work in progress.

Sorry for adding to a closed issue, @ZeroQI, I just somehow felt the need to write a response to the request. Still being severely sick, I blame my high fever ;-)

**Comment by ZeroQI** [comment]
Don't be sorry, and take good care of yourself.

**Comment by jvmunhoz** [comment]
> You don't answer the question of which season and episode should be assigned to the naming convention you invented...I cannot make Plex support something not a season and not a special...

I meant in a next post depending on the answer. I needed to know if making Plex support something not a season and not a special was even possible before I even suggested something... Since it doesn't, it wouldn't matter. 

But thanks for the answer, I'm new to plex and even more so to the technical aspects of the metadata agents. That's good information

> Your issue stems from confusing the concepts of _seasons_ and _series_; anime, as it is produced in Japan, does not use the concept of _seasons_ -instead, what you consider a season is considered a new _series_ in the franchise. Each series has its own specials (or not) that are associated with it.
> 
> OVAs are generally categorized as their own independent entry in the franchise, even when they only have a single episode, as they are produced separately, and are not associated directly with a specific series.

Yes, I'm aware of it. I'm just used to call them seasons when they are direct continuations though. I do separate them as different entries in my library.

> To use your example, the **Akagami no Shirayuki-hime** franchise currently consists of three series/entries:
> 
> * **Akagami no Shirayuki-hime** - 1-cour series
> * **Akagami no Shirayuki-hime: Nandemonai Takaramono, Kono Page** - 1-episode OVA
> * **Akagami no Shirayuki-hime (2016)** - 1-cour series
> 

The only thing I consider as the exactly same series are those cases in which the "seasons"(let's call them that for easyness sake) are separated by 1 cour. They were obviously made to be a single season but were divided for some commercial reason. In which case I actually prefer the "western" nomenclature.


> But it is impossible to have a metadata agent follow an organizational system based entirely on your own personal preference or interpretation of associations, as there is no metadata source that uses such a structure. The closest you might get is Shoko, the new iteration of which has been under development for over a year now, as it identifies episodes by their file hashes, and so, theoretically, could support any file organization scheme, but the current version is still very much a work in progress.

As I said to ZeroQI, I'm actually new to the plex system itself and even more so to the technical aspects of the metadata agents. So thanks for the tips, I will look into it. But I think I can achieve the results I want by the use of collections (which I actually learned about yesterday) which is a much easier solution.
 
> Still being severely sick, I blame my high fever ;-)

Get well soon!

**Comment by ZeroQI** [comment]
Unlike other metadata player (kodi, emby, Plex), my scanner allows movies in series library, normaly you need to split them (even with plex default scanner), so that makes it easier

You can use in the same library anidb and tvdb numbering with my agent, should help

You can put the series together in a grouping folder (root/Collection title/title/title ep01.ext) and it will put it in a collection for you automatically (pretty sure most users are unaware) but scanning will be slower. you can use collection settings to order based on sort title and edit it so have your series in that collection in order...

I made some forced id modes (see scanner readme) to show with season or as tvdb anidb numbered series, that should take care of most needs, and way more than any other metadata ecosystems.

If you edit the library settings, you can set the following:
- hide items in collection so it only show the collection at root level
- Hide single season folders

That for me is the cleanest display removings useless folders and single entry per series/collection at root level

**Comment by jvmunhoz** [comment]
> Re-read your posts,i missed you mentionning you were new...

I didn't mention it in my first post haha

> Unlike other metadata player (kodi, emby, Plex), my scanner allows movies in series library, normaly you need to split them (even with plex default scanner), so that makes it easier with my scanner
> 
> You can use in the same library anidb and tvdb numbering with my agent, should help as normally it's Either AniDB OR TheTVDB...
> 
> You can put the series together in a grouping folder (root/Collection title/title/title ep01.ext) and it will put it in a collection for you automatically (pretty sure most users are unaware) but scanning will be slower. you can use collection settings to order based on sort title and edit it so have your series in that collection in order...
> 
> I made some forced id modes (see scanner readme) to show with season or as tvdb anidb numbered series, that should take care of most needs, and way more than any other metadata ecosystems.
> 
> If you edit the library settings, you can set the following:
> 
> * hide items in collection so it only show the collection at root level
> * Hide single season folders
> 
> That for me is the cleanest display removings useless folders and single entry per series/collection at root level, grouping movies and series in one library and collections.
> 
> You can put videos in an Extras folder, but they will be skipped
> Movies/OADs just need the same title as the folder they are in (you can add tags in square brackets, they are removed)

I may not know much about plex but I read the read.me very carefully haha.

When organizing the collections, I set them up manually by adding the tags. Besides that, yours suggestions are about the same conclusion I reached after fiddling with Plex this morning. 

Thanks for taking your time to help me!

**Comment by purposelycryptic** [comment]
Thanks for the kind wishes, you two :-)

 > But I think I can achieve the results I want by the use of collections (which I actually learned about yesterday) which is a much easier solution.

Collections are a pretty awesome feature, and HAMA's ability to create them based on AniDB series relations (in addition to those statically defined in ScudLee's anime-lists) is one of my favorite features added to it since I first started using it.

Here is an example of my **Akagami no Shirayuki-hime** Collection (taken from the webapp on my phone - I haven't updated my Plex server in a while to avoid the whole issue with plug-in support being removed, so it may look different for you):

![Screenshot_20190922-115705_Chrome](https://user-images.githubusercontent.com/9452779/65390977-75bd7f80-dd31-11e9-85c3-07ff92053ad5.jpg)

The names are only clipped because this is on my phone and not my PC (sadly getting out of bed has become a major exercise for me these days, especially atm, because I've caught the flu thanks to my immunosuppressants, so I get to be doubly sick \*\*grrr\*\*). Each entry can still have its own specials (and even seasons), although I have mine set up so that single-season series fo directly to the episodes. Here's an example of a collection that contains a series that has its own specials, **Mahouka Koukou no Rettousei**:

![Screenshot_20190922-122441_Chrome](https://user-images.githubusercontent.com/9452779/65391249-ed40de00-dd34-11e9-92bd-61b4793ac275.jpg)

The series and the movie each have their own entry, and if we open up the series:

![Screenshot_20190922-122715_Chrome](https://user-images.githubusercontent.com/9452779/65391257-19f4f580-dd35-11e9-8f61-4608aea5c953.jpg)

It has its own *Specials* season, which is where the Blu-ray specials live.

I really like the system, personally - the only thing that triggers my OCD is that Plex automatically appends "Collection" to the end of the name of a collection in certain views (but not all!), and HAMA automatically names collections with the same suffix, to distinguish it from the series itself, so in those certain views, you end up seeing things like  **Mahouka Koukou no Rettousei Collection Collection**. I ended up modifying my version of HAMA so as to not add "Collection" to the collection name, but only because I lack the means to keep Plex from adding it in those views, since it's closed-source.

... Hopefully that was helpful in some form, I tend to ramble on a bit once I get started when I'm sick - possibly a preview of how I'll end up 24/7 when I'm in my 70's ;-)

**Comment by ZeroQI** [comment]
If you share your fix i can include it

**Comment by EndOfLine369** [comment]
Note you can also add "AnimeLists" in your pref list for collections. Anidb series that are all against the same tvdbid are named under the series listed under S1E1 in tvdb as a collection. I have this added at the end of the pref list as a last catch if other sources don't have it setup in a collection. This is not a default as could potentially create unwanted collections but I found it to be fine as a last option in the pref list.

My Pref:
Prefs[collections ] = Local, AniDB, TheMovieDb, TheTVDB, AnimeLists (Default: Local, AniDB, TheMovieDb, TheTVDB)

@ZeroQI you didn't want this option in the pref as a default but that was a while ago. Should we get it added in as a default? or at least better noted in the readme as it is not clear that it is available.

**Comment by ZeroQI** [comment]
@EndOfLins369 The readme needs work possibly. As a fallback that's a good idea, like you have.
I like collections, you can hide them or hide items in collections...
as it is only as fallback, there is no downside now. Removed TheTVDB as it give no collection field (just searched the code for 'collection')

Updated metadata.txt (didn't expect many to read it) and default settings

**Comment by jvmunhoz** [comment]
Thanks @purposelycryptic , that is the sort of organization I was after. I ended up thinking something along those lines this morning, but haven't had the time to actually implment it on my collection yet. It sure is nice looking.


> Here is an example of my **Akagami no Shirayuki-hime** Collection (taken from the webapp on my phone - I haven't updated my Plex server in a while to avoid the whole issue with plug-in support being removed, so it may look different for you):

Plug-in support being removed? What do you mean?

**Comment by ZeroQI** [comment]
Plex annonced it will retire plugins but i think it is about steaming plugins, and not metadata agents

**Comment by jvmunhoz** [comment]
I'm having issues with some anime metadata. Do I post them here or create a new issue?

**Comment by ZeroQI** [comment]
You post in the forum to let other people help unless you are sure the agent or scanner has an issue

**Comment by jvmunhoz** [comment]
[This one? ](https://forums.plex.tv/t/absolute-series-scanner-for-anime-mainly/70289/816)

**Comment by ZeroQI** [comment]
if a scanner issue, yes
if an agent issue: https://forums.plex.tv/t/rel-http-anidb-metadata-agent-hama/40470/1931
