### ISSUE TITLE
How to use DVD order from TVDB ?

### ISSUE THREAD

**Issue by StudioEtrange** [ZeroQI/Absolute-Series-Scanner#236]
How to use DVD order from TVDB with absolute series scanner

**Comment by ZeroQI** [comment]
The same way as with the default Plex series scanner, although it has nothing to do with the scanner, as the episodes on disk stay with the normal ordering...

It is a third party agent setting, agent which I never said I supported
Why are you creating a bug report for that instead of asking the forum?
