### ISSUE TITLE
Incorrect episode matching for Psycho Pass 3

### ISSUE THREAD

**Issue by localh0st-** [ZeroQI/Absolute-Series-Scanner#238]
C:\Anime\Psycho-Pass\Season 3\[HorribleSubs] PSYCHO-PASS 3 - 01 [720p].mkv
Shows up as Season 3 Episode 3

Similar issue with Special 7- Special Crime Investigation Unit. All episodes show up as Episode 1

**Comment by ZeroQI** [comment]
"C:\Anime\Psycho-Pass\Season 3\[HorribleSubs] PSYCHO-PASS 3 - 01 [720p].mkv" shows up as Season 3 Episode 3. It has season folder 3 so that is correct, and after removing the series name from the filename the first number encounter is the episode number: 3

Working as designed. you have to remove the "3" from the filename...
There should have been a security when too many ep numbers are turning up but if all files have different titles or too litle files in folder, it pass through...

name your series folder the same as the files and that should fix Special 7...

I wonder what i have to put in the readme to have people reporting issues attach the scanner log the scanner creates for each series...

**Comment by EndOfLine369** [comment]
@ZeroQI, you can add in issue templates that tell just that and put in questions that need to be answered.

https://github.com/ZeroQI/Absolute-Series-Scanner/issues/templates/edit
https://github.com/ZeroQI/Hama.bundle/issues/templates/edit
