### ISSUE TITLE
Jellyfin Support

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [ZeroQI/Absolute-Series-Scanner#248]
I would absolutely love to see Jellyfin plugin support for Absolute Series Scanner.
Jellyfin is a completely open source fork of Emby. Gaining lots of attraction, also their subreddit just surpassed Emby's numbers in comparison. Many users moving from Plex as well due to Plex's proprietary state, privacy concerns, features being removed, clunky ui, etc. I would highly reccomend Jellyfin support, as it would be a plugin Jellyfin could benefit greatly from.

**Comment by ZeroQI** [comment]
Plugins in JellyFin are not in python like Plex and it doesn't support scanners... 
You do not link to API nor plugin development information... 

You Sir, are not using fact base logic.
Please do not vote Trump again.

**Comment by mildgrim** [comment]
Hello Mr. Brisson, I thought I'd revisit this question now that Jellyfin is far more mature and its position in the 'market' more established. 

I too would love to see Jellyfin support and wanted to inform you that much has changed since this issue was closed. 

To adress your objections from before:

1) Jellyfin does support Python, sort of, it supports IronPython as it can compile to net6.0 which is what is actually supported. 
2) For scanners there is no interface defined directly but I think this project could either fit in as a post scan step, depending on what data the scanner makes available in that interface. If that proves to be a no-go then there are other options. Tough I'm no expert.

Here is the requested plugin development information:

https://github.com/jellyfin/jellyfin-plugin-template

And here is the API documentation:

https://api.jellyfin.org/

Thank you for your time and have a great day! 
Take care,
Sebastian Mildgrim

**Comment by ZeroQI** [comment]
I looked at https://github.com/jellyfin/jellyfin-plugin-anidb and this needs compiling and dot NET
Metadata agent is possible but plex i the obly one allowing custom scanners, and all metadata based systems are based on the premice there is a series folder with the episodes inside or in seasons subfolders. To my knowledge the Absolute Series Scanner is the only softWare going against that trend and Plex default behaviour, and does it atthe expense of caching for grouping folders for example...

No go, but feel free to reuse the code for a potential Jellyfin agent
