### ISSUE TITLE
Series foldername including "S0x" season issue

### ISSUE THREAD

**Issue by IIeTp** [ZeroQI/Absolute-Series-Scanner#249]
Greetings! I have a large library of TV shows, I have no access to change the names, so I ask for help. If you agree to help, I know where the donations link. Most seasons are defined as the first. Examples in the logs.
[_root_W -UNLIMITED-serials-bdremux-teamhd.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008666/_root_W.-UNLIMITED-serials-bdremux-teamhd.filelist.log)
[_root_W -UNLIMITED-serials-bdremux-teamhd.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008667/_root_W.-UNLIMITED-serials-bdremux-teamhd.scanner.log)
[Agents.of.S.H.I.E.L.D.S01.BDRemux.1080p.2xRus.Eng.HDCLUB.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008668/Agents.of.S.H.I.E.L.D.S01.BDRemux.1080p.2xRus.Eng.HDCLUB.filelist.log)
[Agents.of.S.H.I.E.L.D.S01.BDRemux.1080p.2xRus.Eng.HDCLUB.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008670/Agents.of.S.H.I.E.L.D.S01.BDRemux.1080p.2xRus.Eng.HDCLUB.scanner.log)
[Agents.of.S.H.I.E.L.D.S02.BDRemux.1080p.2xRus.Eng.HDCLUB.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008671/Agents.of.S.H.I.E.L.D.S02.BDRemux.1080p.2xRus.Eng.HDCLUB.filelist.log)
[Agents.of.S.H.I.E.L.D.S02.BDRemux.1080p.2xRus.Eng.HDCLUB.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008672/Agents.of.S.H.I.E.L.D.S02.BDRemux.1080p.2xRus.Eng.HDCLUB.scanner.log)
[Breaking Bad S01 BDRemux.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008673/Breaking.Bad.S01.BDRemux.filelist.log)
[Breaking Bad S01 BDRemux.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008674/Breaking.Bad.S01.BDRemux.scanner.log)
[Breaking Bad S03 BDRemux.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008676/Breaking.Bad.S03.BDRemux.filelist.log)
[Breaking Bad S03 BDRemux.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4008677/Breaking.Bad.S03.BDRemux.scanner.log)

**Comment by ZeroQI** [comment]
Working as designed
- S01 is Special 01 using AniDB numbering, it is not a proper season folder numbering

Supported naming
- Breaking Bad\3x05 Mas\BDMV\STREAM
- Breaking Bad\Season 03\e05\BDMV\STREAM
- Agents.of.S.H.I.E.L.D\Season 02\E04\BDMV\STREAM
- Agents.of.S.H.I.E.L.D\S02e04\BDMV\STREAM

So you can add to plex server the custom scanner, but not change the folder names ? That is tricky...
i guess i could support S0x as folder season but it is messy, not following guidelines and needing a redesign of the logic so i leave this bug report open for when i have time

**Comment by IIeTp** [comment]
> So you can add to plex server the custom scanner, but not change the folder names ? That is tricky...
Exactly. As with read-only access.

Could I motivate additionally by donating you? Would that help? Tell me how much.

**Comment by ZeroQI** [comment]
Impacted series folder:
- Saka.no.ue.no.kumo.[Season_3].2011.1080i.Bluray.Remux-TeamHD\
- Agents.of.S.H.I.E.L.D.S01.BDRemux.1080p.2xRus.Eng.HDCLUB\E02-0.8.4\BDMV\STREAM
- Agents.of.S.H.I.E.L.D.S02.BDRemux.1080p.2xRus.Eng.HDCLUB\E16 - Afterlife\BDMV\STREAM
- Breaking Bad S01 BDRemux\102 Cat's In The Bag\BDMV\STREAM
- Breaking Bad S03 BDRemux\313 Full Measures\BDMV\STREAM

Is it because downloaded files are torrent sourced and cannot be renamed as they are being shared? If so, the folders could have been renamed at the download launch time...

Supporting season folders in series name is doable but
- season in square brackets is bad, as square brackets are scrubbed: [Season_3]
- season prepending ep number: S01\102, S03\303... As some series have more than 99 episodes per season, using 102 to mean s01e02 is wrong and will not be supported, resulting in 102 seen as ep 102... 

Donation would help definitely, but i need to have the issue corrected before accepting as i have little free time. BDrip folders working as expected btw?

Notes for me:
- lines 534-547 check season folder. Can check if no season folder found if series folder only contain 'Season_xx' or 'Sxx'. workaround for 102/303 numbering if season folder in the series foldername?

**Comment by IIeTp** [comment]
I wrote you additional information in the mail. Also, you can use [this](https://github.com/filebot/data) repository to improve your scanner

**Comment by ZeroQI** [comment]
I haven't forgotten this request, but it requires two opposite behaviour: 
- AniDB series containing S2 in the series name, to be considered season 1 ('Koukaku Kidoutai: SAC_2045 S2', 'BanG Dream S2', ...)
- TheTVDB series containing S2 in the series name, to be considered season 2 ('Breaking Bad S03', 'Agents.of.S.H.I.E.L.D.S01'). If TheTVDB is the agent and no season folder is detected, we could read the season off the series folder, but that is a first for a scanner to check the agent version to change the behaviour...

Lines for seasons detection
- 0064-0069
- 0536-0549
- 1109-1116

Here is my attempt to be inserted Line 550: 
```
  match = cic(r'^(?P<show>.*?)[ _\.][sS](?P<season>\d{1,2}).*$').search(reverse_path[-1])
  if not folder_season and Dict(PLEX_LIBRARY, root, 'agent', default="")=='com.plexapp.agents.thetvdb' and match and match.group('season'):
    reverse_path[-1], folder_season = clean_string(match.group('show')), match.group('season')
```

**Comment by ZeroQI** [comment]
@IIeTp Any feedback on the code correction pasted above?
