### ISSUE TITLE
TVDB Change - alternate order

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#250]
Hi @ZeroQI  -- is the scanner able to handle alternate orderings on TheTVDB? With the re-airing of [Re:ZERO](https://thetvdb.com/series/re-zero-starting-life-in-another-world), instead of a separate entry, [they are making a 'Director's Cut' alternate ordering](https://forums.thetvdb.com/viewtopic.php?f=18&t=61465&p=167625&hilit=re%3Azero#p167625).

I don't even know where to begin how to account for that (other than use AniDB) or if ScudLee will be able to as well.

**Comment by ZeroQI** [comment]
@sven-7 the alternate series was deleted as expected from thetvdb, so technically a director's cut exist with 1 episode in it [https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1]
We need a completed entry in thetvdb to see a clear case scenario, as i cannot tell if the alternate ordering differs or if the API allows pulling data from it...

**Comment by sven-7** [comment]
It sounds like TVDB is making a whole lot of questionable changes in general. Absolute Numbering is getting redone. There will now be “absolute” which sounds like just episodes that air in a season. Then official, which is absolute + specials in order. There will be Director’s Cut too. Unsure if this is all getting pushed out over the V3 API or not.

**Comment by ZeroQI** [comment]
If the API V2 still works i don't think we should we care, unless it brings usable functionality (absolute numbering without specials could be usable) 
I need an API XML output to see if it is usable, and documented. Cannot see documented v3 calls to get discussed metadata so closing at this point.

**Comment by Hakujou** [comment]
Hello,

In the meantime, is there a way to achieve proper mapping of Re:Zero Director's Cut while still having "Classic" version ?
I tried to number it O1 or S00E401 in Specials folder, but as it's a multiple seasons, my understanding is that AniDB is not used to fetch metadata, therefore it's just listed as "other 401".

Also tried to map the series using anidb/2/3/4, no luck so far. Is there a trick so I can get metadata of those Director's Cut episodes, either from TVDB or AniDB ?

Thanks

**Comment by ZeroQI** [comment]
Did you try: "Re Zero s00e01 title.director's cut.ext"? Both files would be available from Plex...

Anidb will be used by mapping, not as numbering, tvdb specials and season numbering will be used if season number 2+ exists.

It would have helped to have anidb or TheTVDB links for said episodes/seasons as I am on my phone, so it's painful to search...

O1 should work if using anidb id or single season.
Can force tvdbid with single season to match this entry:
https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1

**Comment by Hakujou** [comment]
Thanks for this. I missed that issue, but as far as I can tell, this only works if each season gets its own entry.
I can't really use this approach (because I use Sonarr to retrieve episodes, which can only rely on TVDB, and therefore must use season folders.

I tried to rename it to: "[Erai-raws] Re.Zero kara Hajimeru Isekai Seikatsu - Shin Henshuu-ban - S00E01 [1080p][Multiple Subtitle].Director's Cut.mkv" (I'd like to keep file name as close as the original file as possible), it resolves to S00E01, which is "Re:zero kara Hajimeru Break Time - 01" (which looks normal, since S00E01 is indeed this episode on TVDB: https://thetvdb.com/series/re-zero-starting-life-in-another-world/episodes/5572905).

Sorry for the link, I forgot to include them, will do next time.

Is there a way to force the use of anidb metadata for specials on a multi-season shows ?
