### ISSUE TITLE
Reverse anidb2 matching

### ISSUE THREAD

**Issue by Ether009** [ZeroQI/Absolute-Series-Scanner#257]
The anidb2 matching will take an anidb id, and present it in plex as if it was tvdb names and numbers. But any chances of getting one that takes tvdb id and numbering, but presents it as anidb? Like, take the 4 tvdb seasons of Sword Art Online and present get it in plex as the 4 anidb shows those seasons correspond to? This would allow the use of things like Sonarr and Radarr for library management, while maintaining anidb sorting.

**Comment by ZeroQI** [comment]
tvdb is good enough for Sonaar but Plex need to support anidb numbering on same files?
It's complicated enough as we speak...
I do not see much benefits to be fair...

**Comment by Ether009** [comment]
It's good enough if you like their numbering for sure. But if one wants to use anidb series names and such, while still having sonarr, then it's pretty much a lost cause since you can't get sonarr to sort any other way than the tvdb way, though you can get it to not touch the filenames but the folders are then still used by plex for sorting and matching so it still ends up with tvdb sorting for show and seasons that way.

**Comment by ZeroQI** [comment]
See it another way, this scanner is the only ecosystem that can display both anidb and TheTVDB together, and can display anidb series as TheTVDB, using various modes that only exist with this scanner' and are more used than what I expected.

https://github.com/Sonarr/Sonarr/issues/365

If you use sonar, it is linked to TheTVDB. If you do not like their numbering, why use it?

One should be grateful sonarr work at all with anime... There use to be no such option...

Is there is some library management that use anidb? That would solve the issue...

The scanner is not meant to download json/xml files for sorting. I did it for tvdb2/3 mode initially, and used other modes to assist users.

I do not feel there is a market for this request I find weird. Things are complicated enough and both agent and scanner need to support the metadata flawlessly and take do not have enough time nor drive to solve current open tickets in a timely manner.

Could it be done? Technically yes. Downloading scudlee, then every anidb  xml for present files at least, leading to being banned potentially, label series separately...

If you want data that way, you would have to download torrent rss for series instead of using sonarr...

I am going to close this ticket as I feel either sonar thetvdb display is tolerable or not. You cannot have it both ways. I see no huge demand for tvdb to anidb compared to the other way around...
