### ISSUE TITLE
Anime Season Part recognition

### ISSUE THREAD

**Issue by HonestySoftware** [ZeroQI/Absolute-Series-Scanner#261]
I tried to let ASS / Hama sort "Shokugeki no Souma" but I'm getting an issue. 

There are currently 
Season 1
Season 2
Season 3
Season 3 Part 2
Season 4

I tried to put Season 3 as Season 4 and Season 4 as Season 5, but instead of creating a Season 5, it threw them into "Spceials". Is there a solution to solve this?
Season 3 Part 2 is listed with own episode numbers instead of continueing from Part 1 as you can see: https://anidb.net/anime/13658

Hope someone has a solution

**Comment by ZeroQI** [comment]
If you use seasons then you use TheTVDB numbering yet to quote AniDB for the numbering... Follow TheTVDB numbering since you are using seasons.

If the folder content didn't change, the scanner would not detect the folder name change. That would explain your issue.

You have not included scanner logs despite them clearly listed in the readme. As you failed to provide scanner logs proving a mismanagement by my scanner, closing this bug report.
