### ISSUE TITLE
TV series do not detected

### ISSUE THREAD

**Issue by IvanShift** [ZeroQI/Absolute-Series-Scanner#273]
Hello!
I found new problem, TV series "Devs"  do not detect name. 
What should I correct at the name of folder (it has name "Devs.S01.WEB-DL (1080p).RusEng")? 
I have  practically the same name of folder "The.Lost.Room.S01.2006.720p.WEB-DL_MediaClub" and this tv series name detected fine.

[Devs.S01.WEB-DL (1080p).RusEng.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4551728/Devs.S01.WEB-DL.1080p.RusEng.filelist.log)
[Devs.S01.WEB-DL (1080p).RusEng.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4551729/Devs.S01.WEB-DL.1080p.RusEng.scanner.log)

**Comment by ZeroQI** [comment]
Logs indicate series title to be  "Devs.S01.WEB-DL (1080p).RusEng" due to atrocious naming
If you mean the series didn't match, that's an agent issue, and working as expected

You have to actually either start renaming your series folders (Devs/Season 1, The Lost Room/Season 1) or putting every tag not in square brackets in the clean-up terms list and let me know so i can add it to the code

Line 102-119 you could add in WHACK_PRE_CLEAN_RAW towards the end (only things sure to not be in any title otherwise put it in WHACK lines 131-136): "WEB-DL", "(1080p)", "RusEng", "MediaClub", "720p", "1080p",

**Comment by IvanShift** [comment]
I create folder Devs and put  "Devs.S01.WEB-DL (1080p).RusEng" folder inside.
Add this string ("WEB-DL", "(1080p)", "RusEng", "MediaClub", "720p", "1080p") to WHACK - array and made new scan. Result are the same. Tv series name not detected 
(![devs](https://user-images.githubusercontent.com/64527940/80607432-27e2c580-8a3e-11ea-9ef8-8eac80438789.JPG)

[Devs.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4552215/Devs.filelist.log)
[Devs.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4552214/Devs.scanner.log)

**Comment by ZeroQI** [comment]
Why creating a scanner bug report when it is an agent matching issue which you can do manually...
why 'Devs/Devs.S01.WEB-DL (1080p).RusEng'?
Why not "Devs"?

**Comment by IvanShift** [comment]
I'm sorry. Please delete this issue.
