### ISSUE TITLE
Season 0 Specials Episode detection issues

### ISSUE THREAD

**Issue by Gumbyohson** [ZeroQI/Absolute-Series-Scanner#280]
I use a format in Sonarr for Naming files: "{Series Title} S{season:00}E{episode:00} {absolute:000} {Quality Title}".
This works fine in season folders but specials this can result in is detecting the file as if it is "E01-E008" as an example. I've read through the full manual a few times and I cant see a way to prevent this besides not using absolute numbering in the file name such as in "Garden of Sinners" S00E01 008".
I attempted to enforce tvdb.id for the show in the specials folder but this still is causing the parsing to missidentify the files episodes.

**Comment by ZeroQI** [comment]
No logs so I don't know exactly which regex or manual detection is triggered, so guessing regex detect the ep as an EP range so the word search prior has failed due to the presence of all these additional numbers ...

No release group would to my knowledge include two separate numberings on the same filename so I would like to avoid altering the code just for you and possibly impact others, and I just don't know which numbering convention should come on top then...
Why didn't you simply put the abs numbering into square brackets so it is scrubbed out?

**Comment by Gumbyohson** [comment]
Hi ZeroQI,

I didn't realise the square brackets would fix this. I'll have to give it a
try. Thanks for the quick response. If there is something specific I can
provide that would help please let me know.

**Comment by ZeroQI** [comment]
Thé scanner logs created in logs folder in a subfolder ? Donation?

**Comment by Gumbyohson** [comment]
This might annoy you but I wanted to say thanks. I dont have much but I sent a donation.
I'm still learning ASS and Hama's quirks to get it working best with my system and I appreciate your time and patience with me.

**Comment by ZeroQI** [comment]
Why would thanks annoy me? At the contrary.
I am temporarily broke so donation is much appreciated, 5€ is one to 2 meals if you shop well.
It also belp keeping me motivated to maintain it, which is important as I do not use it for myself, and have the scanner Hama/YouTube/Lambda agents and I find it more difficult to program nowadays (sleep apnoea or aging, not sure)

You documented propertly enough despite the lack of logs (Plex has awful canner logs so made ASS output readable ones in logs folder, will have to move Hama ones there at some point) so I could guess why you wanted both numbering allowing to find a workaround instead of altering the code which is complex enough to be fair.

Thank you.
