### ISSUE TITLE
Forcing series id is matching a different id.

### ISSUE THREAD

**Issue by Renari** [ZeroQI/Absolute-Series-Scanner#294]
When attempting to match Sword Art Online: Alicization - War of Underworld (2020). I wasn't getting any matches. I read in the readme you can force a match using the guid.

https://anidb.net/anime/15146

The above is the entry I tried to force the match in by placing `[anidb-15146]` into the search dialog. This results in 1 match like so:
![image](https://user-images.githubusercontent.com/1839179/87242245-db7e1380-c3f8-11ea-9e00-1249a232bc04.png)

However upon selecting this match the resulting metadata appears to have been grabbed from different seasons of Sword Art Online, the show description and art grabbed from the original Sword Art Online show and the first episode data appears to be grabbed from Gun Gale Online.

![image](https://user-images.githubusercontent.com/1839179/87242426-94911d80-c3fa-11ea-9ef5-a00b1137c47d.png)

Inside my ASS log for this category I see 2 entries for this show:
```
Scanner call - root: '/media/media/Anime', path: 'Sword Art Online - Alicization War of Underworld Season 2', dirs: '0', files: '1'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
No forced ID - file: /media/media/Anime/Sword Art Online - Alicization War of Underworld Season 2, present: False
misc: 'sword|art|online|alicization|war|of|underworld|s02e01|mkv'
misc_words: '()', misc_count: '{'s02e01': 1, 'art': 1, 'of': 1, 'mkv': 1, 'sword': 1, 'online': 1, 'underworld': 1, 'alicization': 1, 'war': 1}'
"Sword Art Online - Alicization War of Underworld Season 2" s0002e001 "[Judas] Sword Art Online Alicization - War of Underworld - S02E01.mkv" "1"
```
and
```
Scanner call - root: '/media/media/Anime', path: 'Sword Art Online - Alicization War of Underworld Season 2', dirs: '0', files: '1'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
No forced ID - file: /media/media/Anime/Sword Art Online - Alicization War of Underworld Season 2, present: False
misc: 'sword|art|online|alicization|war|of|underworld|s02e01|mkv'
misc_words: '()', misc_count: '{'s02e01': 1, 'art': 1, 'of': 1, 'mkv': 1, 'sword': 1, 'online': 1, 'underworld': 1, 'alicization': 1, 'war': 1}'
"Sword Art Online - Alicization War of Underworld Season 2" s0002e001 "[Judas] Sword Art Online Alicization - War of Underworld - S02E01.mkv" "1"
```

Neither of witch show a forced id.

**Comment by ZeroQI** [comment]
If you do not want your episode showing as season 2 in Plex, and to assign TheTVDB title "Sword Art Online" as it is now, then 
you are doing it wrong, as it works as designed...

"[Judas] Sword Art Online Alicization - War of Underworld - **S02**E01.mkv" =>Your episode use TheTVDB numbering, season 2 therefore using thetvdb id to march since it has more than one season (**AniDB only have single season** and specials)

Being TheTVDB, it will match to the TVDB series entry, which encompasses both seasons 
- https://thetvdb.com/series/sword-art-online
- the series summary match the TVDB id of the series, therefore working as designed

The SCANNER has not got access to what is specified at the AGENT level:
- ASS can detect the ID at file level (Series folder/tvdb.id) or in the folder name "Sword Art Online [tvdb-259640]" 
- it is ok to manually force through the agent if the scanner is not meant to change the season or episode number
- You MAY BE able to correct without renumbering the files by providing the SCANNER (Series folder/tvdb.id or folder name with " [anidb-15146-s1")

**Comment by Renari** [comment]
Alright, I guess I misunderstood the readme I was under the impression that forcing the match to a specific guid made the episode naming irrelevant. Sorry for the bother.
