### ISSUE TITLE
Detect HorribleSubs naming convention as seasons

### ISSUE THREAD

**Issue by reconman** [ZeroQI/Absolute-Series-Scanner#304]
**Is your feature request related to a problem? Please describe.**
The HorribleSubs group currently uses absolute numbers for their 2nd and 3rd season episodes. For example, `[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 26 [1080p].mkv` instead of `[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - S02E01.mkv`

One episode shows up as season 1, episode 26 and the other one as season 2, episode 1.

**Describe the solution you'd like**
My anime list tracker Taiga uses a text file to map high episode numbers to different seasons: https://github.com/erengy/anime-relations. The file is updated from the github repository on every startup.

**Describe alternatives you've considered**
I can't think of any alternatives. Renaming the episodes by hand is not something I want to do all the time.

**Additional context**

**Comment by ZeroQI** [comment]
I already use an anidb to tvdb mapping file so I won't add yet another mapping. You have to use anidb or tvdb numbering.

I would just rename the series folder name in this case
[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu
[tvdb-xxxxxx-S02e-25] / Re Zero kara Hajimeru Isekai Seikatsu - 26 [1080p].mkv

Added benefit is that the tvdb I'd being the same it will gather all seasons under one series.

**Comment by reconman** [comment]
Sorry, what am I supposed to use as folder name? Your message is confusing since [HorribleSubs] is part of the folder name. And where is the syntax for `S02e-25` documented?

**Comment by ZeroQI** [comment]
Apologies, it's tricky to cut and paste on a phone

Re Zero kara Hajimeru Isekai Seikatsu
[tvdb-xxxxxx-s02e-25] / [HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 26 [1080p].mkv

Since the scanner decide the series season and episode number, it is in the scanner readme https://github.com/ZeroQI/Absolute-Series-Scanner
Scanner readme / Forced IDs / advanced modes...

So little people read the readme I even put a mention about the rtfm tax in it...

**Comment by Hamuko** [comment]
`Re Zero whatever you want here [anidb-14792-s01e-25]` works if you want to use AniDB without having to rename everything.

>So little people read the readme I even put a mention about the rtfm tax in it...

Pretty sure that's because the README is awful to read. It's a jumbled mess and missing information. For example, there's no indication that you can use the season/episode offset with AniDB and there's no example where the season offset is negative. So if you want to use AniDB without renaming, the README is of little use unless you make a guess about some syntax mentioned in an other instance being applicable somewhere else as well. I only found about being able to add the offset to AniDB data from some random issue in the repository.

**Comment by ZeroQI** [comment]
Plex users are meant to follow either anidb or TheTVDB convention. This is the only ecosystem where you can have both convention and also movies in series libraries...
 Here you don't want to rename a bad episodenaming convention so you have to use a seldomly used and documented feature. 

It is open source.
If you submit a change to the readme I will include it.
