### ISSUE TITLE
Naming Convention for Movies

### ISSUE THREAD

**Issue by wahab14131211** [ZeroQI/Absolute-Series-Scanner#308]
Hello, 

I recently started going through my Plex Anime library to reorganize my filesystem structure according to the Absolute Series Scanner. However, there are parts of the Readme that i don't quite understand, namely: 
https://github.com/ZeroQI/Absolute-Series-Scanner#one-libray-for-both-movies-and-tv-series

I have a filesystem structure as follows: 
Attack on Titan/
├── Gekijouban Shingeki no Kyojin
│   ├── Gekijouban Shingeki no Kyojin - 01 - Complete Movie.mkv
│   └── Gekijouban Shingeki no Kyojin - 02 - Complete Movie.mkv
├── Season 1
│   ├── [HorribleSubs] Shingeki no Kyojin - 01 [1080p].mkv
│   ├── ...
│   └── [HorribleSubs] Shingeki no Kyojin - 25 [1080p].mkv
├── Season 2
│   ├── [HorribleSubs] Shingeki no Kyojin S2 - 26 [1080p].mkv
│   ├── ...
│   └── [HorribleSubs] Shingeki no Kyojin S2 - 37 [1080p].mkv
└── Season 3
    ├── [HorribleSubs] Shingeki no Kyojin S3 - 38 [1080p].mkv
    ├── ...
    └── [HorribleSubs] Shingeki no Kyojin S3 - 55 [1080p].mkv

The issue i am having is with regards to the 2 movies. If i remove the 'Gekijouban Shingeki no Kyojin' folder altogether, the scanner correctly identifies the 3 seasons, and sorts everything properly. However, when i add this folder containing the movies back, plex groups the 2 movies into a single file (it assumes they are the same movie), and does not recognize any of the other seasons at all. 

Ideally, in plex, i would like to see a single series "Attack on Titan" with the 3 seasons identified correctly, and a 4th "group" containing the movies. **In this situation, what should I name the 2 movie files, and where should they be stored.**

For reference, i am using the HAMA plugin and here is the aniDB listing for the 2 movies: https://anidb.net/anime/10583

If you would like, i can also supply the logs for the scanner, but i am just trying to figure out how the scanner would like the files to be named and stored. Not really asking for a fix.

Thank you for taking you time to make this amazing scanner and maintaining it!

**Comment by ZeroQI** [comment]
Attack on Titan/
├── Gekijouban Shingeki no Kyojin
│   ├── Gekijouban Shingeki no Kyojin - 01.mkv
│   └── Gekijouban Shingeki no Kyojin - 02.mkv

A movie can't have 2 episodes, it's a series of two theatrical episodes, as otherwise you would have 1 episode in the AniDB entry

Since you use seasons, the agent use TheTVDB numbering as basis, no using TheTVDB numbering for specials would make sense or anidb2 mode for the series of two movies folder so it gets translated to S00E22-23

https://www.thetvdb.com/series/attack-on-titan/seasons/official/0
