### ISSUE TITLE
How to scan like this?

### ISSUE THREAD

**Issue by Andor233** [ZeroQI/Absolute-Series-Scanner#373]
https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1

It is season 1 in anidb, but in tvdb it is in the Director's Cut

**Comment by ZeroQI** [comment]
TVDB alt numbering is unsupported.
https://anidb.net/anime/11370 AniDB O1 to O13 is supported

**Comment by Andor233** [comment]
Yeah I mark it as AniDB O1 to O13, but it can't map to the tvdb, And scan nothing.
![image](https://user-images.githubusercontent.com/16273755/132949478-004ee2f1-b31b-45d5-bdfc-be960f0a23f2.png)

**Comment by ZeroQI** [comment]
It shows in Plex therefore scanned properly.

Do you mean it doesn't pull metadata from TheTVDB? 
Since there is no AniDB to TheTVDB mapping for alternate numbering, and no support for TheTVDB alternate numbering In the first place,  there is no alternative.

Technically we could create new TVDB modes to account for alt numbering but no mapping so no point really. In this instance one should use the original format and not the director's cut, choosing the later comes with consequences and limitations...

To my knowledge, there isn't any metadata ecosystem currently supporting alternate numbering

Furthermore, the TVDB support will stop beginning of October with the deprecation of TheTVDB API V2 so this should have been the least of your worries...

**Comment by Andor233** [comment]
I see... 
So after October TVDB needs to pay for it?

**Comment by Andor233** [comment]
> It shows in Plex therefore scanned properly.
> 
> Do you mean it doesn't pull metadata from TheTVDB?
> Since there is no AniDB to TheTVDB mapping for alternate numbering, and no support for TheTVDB alternate numbering In the first place, there is no alternative.
> 
> Technically we could create new TVDB modes to account for alt numbering but no mapping so no point really. In this instance one should use the original format and not the director's cut, choosing the later comes with consequences and limitations...
> 
> To my knowledge, there isn't any metadata ecosystem currently supporting alternate numbering
> 
> Furthermore, the TVDB support will stop beginning of October with the deprecation of TheTVDB API V2 so this should have been the least of your worries...

But without TVDB, but anidb still have the metadata and the title, why not pull the metadata from anidb?

But the absolute seq of anime is a problem.

**Comment by Andor233** [comment]
> Yeah I mark it as AniDB O1 to O13, but it can't map to the tvdb, And scan nothing.
> ![image](https://user-images.githubusercontent.com/16273755/132949478-004ee2f1-b31b-45d5-bdfc-be960f0a23f2.png)

How can I pull the metadata from anidb, As you see it scanned properly

**Comment by ZeroQI** [comment]
In October tvdb stops working as I haven't coded tvdb v4 (paying) support.

Create a gitub bug report for your hama metadata question attaching series_title.update.log to see why options title not used from AniDB...

**Comment by Andor233** [comment]
I got it, But with coded, it still needs to pay, Is there any alternative?

**Comment by Andor233** [comment]
Oh I saw the issue in the hama
