### ISSUE TITLE
Pokemon [anidb2-230] Not mapping correctly

### ISSUE THREAD

**Issue by Dalarialus** [ZeroQI/Absolute-Series-Scanner#385]
I'm not sure if I'm doing something wrong, but I'm unable to get Pokemon to behave as expected using anidb2 mode.

Expected behaviour: All files in folder /Pokemon [anidb2-230]/Pokemon - #### - Title [codec].mkv format should appear as seasons on Plex with full metadata from TVDB.

Observed behaviour: All files appear as one large season, with no episode metadata being pulled for any episode beyond ZeroQI/Hama.bundle#82 (which incidentally is the end of Season 1 on TVDB.

Am I doing something wrong here? The rest of my anime library appears to be mapping correctly with no real need for intervention.

**Comment by Dalarialus** [comment]
Sorry about that. Apparently too many night shifts have seriously impaired my ability to read. An appropriate RTFM tax has been paid >.<

I've attached some log files - hopefully these are the right ones to be able to tell what's happening?

[_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741704/_root_.scanner.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741707/Plex.Media.Scanner.log)
[_root_.agent.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741710/_root_.agent.log)
[_root_-media-ANIME.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741712/_root_-media-ANIME.filelist.log)
[_root_-media-ANIME.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741714/_root_-media-ANIME.scanner.log)
[Pokemon.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741716/Pokemon.agent-search.log)
[Pokemon.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741717/Pokemon.agent-update.log)
[Pokemon.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741718/Pokemon.filelist.log)
[Pokemon.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741719/Pokemon.scanner.log)

**Comment by ZeroQI** [comment]
root-media-ANIME.scanner.log show 
- /media/ANIME/Pokemon/Pokemon [anidb2-230]

Series folder alone in grouping folder, more likely to trigger bugs, sould work without 'pokemon' grouping folder maybe...

Pokemon.scanner.log shows all eps in season 1 but TheTVDB has only 82 eps in season 1 so scanner is wrong, sould put 83+ in tvdb season folders, to check if it is due to the 4 digit EP number? 

FYI, if changing path, folder content need to change and a rescan done to have scanner react to the change

**Comment by Dalarialus** [comment]
Thanks for the quick reply!

I've removed the files from the library folder, rescanned, optimised the database, cleaned bundles, renamed the files to make the episode numbers three digits and placed the folder straight into root (without a grouping folder).

On rescanning, the issue seems to still be there. The episodes are still showing up in one large season.

[_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741874/_root_.scanner.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741878/Plex.Media.Scanner.log)
[_root_.agent.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741880/_root_.agent.log)
[_root_-media-ANIME.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741881/_root_-media-ANIME.filelist.log)
[_root_-media-ANIME.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741883/_root_-media-ANIME.scanner.log)
[Pokemon [anidb2-230].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741887/Pokemon.anidb2-230.filelist.log)
[Pokemon [anidb2-230].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741888/Pokemon.anidb2-230.scanner.log)
[Pokemon.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741889/Pokemon.agent-search.log)
[Pokemon.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741890/Pokemon.agent-update.log)
[Pokemon.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741891/Pokemon.filelist.log)
[Pokemon.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741892/Pokemon.scanner.log)
[Pokemon [anidb2-230].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741893/Pokemon.anidb2-230.agent-search.log)
[Pokemon [anidb2-230].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7741894/Pokemon.anidb2-230.agent-update.log)

**Comment by ZeroQI** [comment]
Pokemon [anidb2-230].scanner.log does all episodes in one single folder indeed still.
`mappingList: {'s0e1': 's0e23', '**defaulttvdbseason_a': True**, 'defaulttvdbseason': '1', 'episodeoffset': '0'}`
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
- line 831 for anidb2 mode, creates mappingList 
- line 385 add_episode_into_plex

Mapping file use 'a' for defaulttvdbseason, therefore cannot map easily since direct mapping is not available
Since you have absolute numbering, tvdb2,3,4 would be a more adequate actually:
- tvdb2 will create tvdb season folder from absolute numbering reseting ep number each season
- tvdb3 will create tvdb season folder from absolute numbering keeping absolute ep number each season
- tvdb4 would create season matching archs defined

tvdb2 mode would be closest to anidb2 behaviour, then: "Pokemon [tvdb2-76703]" should work as designed, but the folder content need to change for the scanner to re-scan the folder withotut cache

**Comment by ZeroQI** [comment]
Did you try "Pokemon [tvdb2-76703]" + Plex danse ?
