### ISSUE TITLE
TVDB4 - Ongoing series

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#41]
Can the scanner handle/is it ready for shows that are ongoing?  How would we list a show that is still going, but we do not know when the "arc" or season will end?

JoJo's Bizzare Adventure:

```
04|075|___|Diamond is Unbreakable
```

**Comment by EndOfLine369** [comment]
It could but shouldn't as is. A number is required in the first 3 columns or all mapping is ignored. And a large number is ill advised.

I have an _idea_ for the scanner to handle this... 
Let me look at the code and get back to you.

**Comment by EndOfLine369** [comment]
@ZeroQI Please take an eye to this.
The below change will help for in any of the tvdb2/3/4 modes.

If the episode number is not present in the mapping (from not setup in TheTVDB or not in the tvdb4 mapping local/online file) and the episode is after the the last episode available in the mapping. It takes the season from that last episode available and applies the season to the unmapped episode.

EX:
If we only had this mapping available:
```
    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|045|Red Ribbon Army Saga
    04|046|057|General Blue Saga
    05|058|067|Commander Red Saga
    06|068|083|Fortuneteller Baba Saga
    07|084|101|Tien Shinhan Saga
```
And we put in an episode 102+, it will apply season 7 to the episode.

And for the above example of running series, we can simply put the start and end episode number as the same start number:
`04|075|075|Diamond is Unbreakable`
So any 76+ episodes get mapped to season 4.

Instead of season 1 like it would currently as it is not in a season folder and in the root series folder. As well as having no mapping to place into another season.

```python
FROM:
  if tvdb_mapping and ep  in tvdb_mapping and season != 0:                 season, ep  = tvdb_mapping[ep ]
  if tvdb_mapping and ep2 in tvdb_mapping and season != 0:                 season, ep2 = tvdb_mapping[ep2]

TO:
  if tvdb_mapping:
    max_ep_num = max(map(int, tvdb_mapping.keys()))
    if   ep      in tvdb_mapping and season != 0:                          season, ep  = tvdb_mapping[ep ]
    elif ep  not in tvdb_mapping and season == 1 and ep  > max_ep_num:     season      = tvdb_mapping[max_ep_num][0]
    if   ep2     in tvdb_mapping and season != 0:                          season, ep2 = tvdb_mapping[ep2]
    elif ep2 not in tvdb_mapping and season == 1 and ep2 > max_ep_num:     season      = tvdb_mapping[max_ep_num][0]
```

**Comment by ZeroQI** [comment]
Putting in the season after the last one mapped would be more flexible as even if you miss the last season entry, it will still work, which will prevent mishaps even if the mapping file update timing is a bit off and even if the season is wrong that way, the episode will get metadata anyway and will be at worst one season apart and consistent with the mapping file anyway

FROM:
  if tvdb_mapping and ep  in tvdb_mapping and season != 0:                 season, ep  = tvdb_mapping[ep ]
  if tvdb_mapping and ep2 in tvdb_mapping and season != 0:                 season, ep2 = tvdb_mapping[ep2]

TO:
  if tvdb_mapping and season > 0 :
    max_ep_num = max(map(int, tvdb_mapping.keys()))
    if   ep  in tvdb_mapping:               season, ep  = tvdb_mapping[ep ]
    elif ep  > max_ep_num and season == 1:  season      = str(int(tvdb_mapping[str(max_ep_num)][0])+1)
    if   ep2 in tvdb_mapping:               season, ep2 = tvdb_mapping[ep2]
    elif ep2 > max_ep_num and season == 1:  season      = str(int(tvdb_mapping[str(max_ep_num)][0])+1)

**Comment by EndOfLine369** [comment]
A season+1 would be fine for new series yet unknown or errant episodes. But once we know a new season is running, I would think it would be best to have the entry as we would also want an entry in the poster xml.

So how about...

In this case, it is a series with mapping but then we get a new season that is not defined in the mapping yet of ep 46+. It would put those into a last season+1 (season 4).
```
    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|045|Red Ribbon Army Saga
```
But if we now know about the new season, the mapping would be updated below and any ep 47+ would be placed into the last season (season 4) instead of as before of season+1 (season 5).
```
    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|045|Red Ribbon Army Saga
    04|046|046|General Blue Saga (running)
```
We would look for the string "(running)" to determine this separation in behavior and set a variable 'last_season_running' of True when "(running)" is seen else False.

Nice reduction :wink: but tvdb_mapping keys are ints and season is an int so fixed back to what I had above below.
```
  if tvdb_mapping and season > 0 :
    max_ep_num = max(tvdb_mapping.keys())
    season_buffer = 0 if last_season_running else 1
    if   ep  in tvdb_mapping:               season, ep  = tvdb_mapping[ep ]
    elif ep  > max_ep_num and season == 1:  season      = tvdb_mapping[max_ep_num][0]+season_buffer
    if   ep2 in tvdb_mapping:               season, ep2 = tvdb_mapping[ep2]
    elif ep2 > max_ep_num and season == 1:  season      = tvdb_mapping[max_ep_num][0]+season_buffer
```

**Comment by ZeroQI** [comment]
Would just have put the new season/arc mapping when a new one comes or a
wider range for ongoing arc in case of eps range already known so we only
need to update after a a new arc starts

Code looks good otherwise

A season+1 would be fine for new series yet unknown or errant episodes. But
once we know a new season is running, I would think it would be best to
have the entry as we would also want an entry in the poster xml.

So how about...

In this case, it is a series with mapping but then we get a new season that
is not defined in the mapping yet of ep 46+. It would put those into a last
season+1 (season 4).

    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|045|Red Ribbon Army Saga

But if we now know about the new season, the mapping would be updated below
and any ep 47+ would be placed into the last season (season 4) instead of
as before of season+1 (season 5).

    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|045|Red Ribbon Army Saga
    04|046|046|General Blue Saga (running)

We would look for the string "(running)" to determine this separation in
behavior and set a variable 'last_season_running' of True when "(running)"
is seen else False.

Nice reduction 😉 but tvdb_mapping keys are ints and season is an int so
fixed back to what I had above below.

  if tvdb_mapping and season > 0 :
    max_ep_num = max(tvdb_mapping.keys())
    season_buffer = 0 if last_season_running else 1
    if   ep  in tvdb_mapping:               season, ep  = tvdb_mapping[ep ]
    elif ep  > max_ep_num and season == 1:  season      =
tvdb_mapping[max_ep_num][0]+season_buffer
    if   ep2 in tvdb_mapping:               season, ep2 = tvdb_mapping[ep2]
    elif ep2 > max_ep_num and season == 1:  season      =
tvdb_mapping[max_ep_num][0]+season_buffer

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZeroQI/Absolute-Series-Scanner/issues/41#issuecomment-226804208>,
or mute the thread
<https://github.com/notifications/unsubscribe/AE7LZRNpDsoJk5YUzahj81Wd2ibRest1ks5qMsAygaJpZM4I39_->
.

**Comment by EndOfLine369** [comment]
I have this codded and will be committing shortly.

**_To recap:_**
If there is a series with mapping but then we get a new season that is not defined in the mapping yet, an episode number past the last mapped episode will be put into the last season+1 (ep 46+ = season 4).
```
    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|045|Red Ribbon Army Saga
```
But if we now know about the new season, the mapping would be updated below with the ending episode number being the same as the starting. The string "(unknown length)" must be added to the season name otherwise it will have the above behavior. With the string added, an episode number past the last mapped episode will be put into the last season (ep 46+ = season 3).
```
    01|001|013|Emperor Pilaf Saga
    02|014|028|Tournament Saga
    03|029|029|Red Ribbon Army Saga (unknown length)
```

**Comment by EndOfLine369** [comment]
Changes committed & added in example entries into the mapping xml.
