### ISSUE TITLE
Purpose of this plugin

### ISSUE THREAD

**Issue by glensc** [ZeroQI/Absolute-Series-Scanner#410]
I was sent here from https://github.com/ZeroQI/YouTube-Agent.bundle/issues/96#issuecomment-1120254531 but I find the purpose of this plugin lacking. Why should I install this plugin? What problem does it solve?

problems:
1. The project description is very minimal "Seasons, absolute mode, Subfolders..."
2. the project readme is kilometers (miles) long, and it starts from like reader should be very very acknowledged about Plex internals. 
3. "Plex scanner responsibilities" is it talking about this plugin, or plex scanner in general?
4. the same for "Plex Agent responsibilities", both lack context

**Comment by ZeroQI** [comment]
1) And ? You already complained it it kilometers long, and you want it longer? You did not even follow the "post in either:" section since you should have posted to the forum page to have other users help you, but you seem to want the main developer to do it...
2) Correct. It is not this agent/scanner responsability to teach you about plex in general or install third party scanner/agent, knowing that is a requirement. 
3) 4) Plex scanner, otherwise would have said Absolute Series Scanner or This scanner. "Plex Scanner" or "Plex agent"doesn't have any ambiguity to me, furthermore the definition doesn't have any youtube specific element to it. 

```
post in either:

[Plex Support thread for Scanner (you are unsure if it is a bug)](https://forums.plex.tv/discussion/113967/absolute-series-scanner-for-anime-mainly/#latest)
[Github issue page (you have a bug)](https://github.com/ZeroQI/Absolute-Series-Scanner/issues)
```
You should have posted in the forum support thread, this is NOT a bug report, other users could have assisted you...
When users do that, it take the time to do something else, and the thread will close after 3 month if no post and i will take that as a confirmation users are not using it and stop support

Why using the scanner for youtube? 
- For Playlists, it put them in the right order as the scanner determine the season and episode number, like any other plex scanner, and can sort per year depending the mode
- Put Playlist id (PL... 2+16/32 chars long) on series folder or season folder (auto-reversing) or channel id on series folder (year used as season, added as date-based unless there are duplicates for the date in which case it choose ep number MMDDxx with XX being incremental) [from the readme]

**Comment by glensc** [comment]
FYI: It is not just me not understanding the purpose and setup:
- https://github.com/ZeroQI/YouTube-Agent.bundle/issues/92#issuecomment-1021660523

**Comment by ZeroQI** [comment]
This is a question suitable for the forums for me.
Other users who actively use the agent.
I have never used the YouTube agent myself, so while I did an ok job I believe, I would do an underwhelming description: it's a metadata agent. Ass when provided the playlist order eps in order, and if using channel number, it sorts using  the publication year as season. Seem like files released on same day cause a bug I can't solve...

**Comment by ohrodr** [comment]
Purely because of reading this exchange I have decided not to investigate the problems I've seen with the app, and instead fork and remove communication with the developer(s) from the equation.  I also think the documentation is terrible, inappropriately structured, and missing necessary elements to make it digestible by consumers.  While I came here to look up whether bugs I've found in this rats nest of code have been resolved I've decided against interactions outside of this comment.  Either way, interactions with others are an important aspect to releasing code into a community that may need support.

Stupid name, terrible code, rude developer.

**Comment by purposelycryptic** [comment]
@ohrodr wow, talk about arrogant. This plugin is great, does exactly what it is supposed to, and I'm deeply grateful to the developer for all the work he has done on both it and HAMA over the years. They've been extremely helpful and quick to respond to issues, as long as one shows a modicum of civility and intelligence.

People like you are exactly why so many projects on GitHub get abandoned - ungrateful, entitled asses who believe the world revolves around then exclusively.

**Comment by ZeroQI** [comment]
@purposelycryptic
- Thanks a lot for your reply to this , I couldn't have put it better myself: "as long as one shows a modicum of civility and intelligence.". I am a grumpy f##k, but if people give a problem statement and logs, i will help despite not using Plex anymore... I must be a fool to support something i don't use myself, to receive messages like that, make me feel like deleting it all...
 
I will accept any pull request in readme or code modification (like the anidb2|3|4 functionality or readme improvement).

To all, feel free to fill a pull request with any clarification you see fit... You can just click edit on the page in github like i do from my phone sometimes with the code, and i will push it to the master code after short review...
I used to modify the readme after each issue, but i noticed people don't read it even if the answer is in it, like where it instructs to post on the forum for use case and questions, and the initial poster created a bug report instead...

@ohrodr
- Why would you fork over terrible code? Use my blank Agent, that you will customize to your liking [https://github.com/ZeroQI/Hama.bundle/releases/download/v1.0/Empty_Agent_template.bundle.7z]
- You are so rude complaining about me being rude, you sir, are a pure true hyprocrit... 
- Type of verbal aggression towards somebody you never interacted with, you might want to mention it to your psychiatrist... 

That sadly reminds me of the Sakuhachi master debacle, in essence, a misplaced Social Justice Warrior getting offended on behalf of other people without reason, wrongly, and with no discerning capacity to handle it and argument logically, and delete themself in the end...
Source: https://www.boredpanda.com/girl-accuses-sony-cultural-appropriation-shakuhachi-bamboo-flute-cornelius-boots/?utm_source=google&utm_medium=organic&utm_campaign=organic]
