### ISSUE TITLE
you should use {} instead of [] for forcing a scanner

### ISSUE THREAD

**Issue by drizzt** [ZeroQI/Absolute-Series-Scanner#420]
You should use {tvdb-XXX} instead of [tvdb-XXX] for forcing a scanner to be compatible with Plex Scanner

**Comment by purposelycryptic** [comment]
Dear God no, at least not as a replacement - I (and likely many, many others) have over 3,000 series using the current naming scheme, and redoing my collection when the current scheme has worked perfectly for years just sounds like a terrible idea.

**Comment by ZeroQI** [comment]
Plex scanner scrap content in square brackets, which is why I chose that initially. Plex recently started to use this convention. 

https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/

You are not addressing why, the cost/benefits of implementing it and why replacing instead of adding support. Closing
