### ISSUE TITLE
4-nin wa Sorezore Uso wo Tsuku - Wrong episode numbers

### ISSUE THREAD

**Issue by DJScias** [ZeroQI/Absolute-Series-Scanner#426]
## Platform

Operating system and version:  Ubuntu 20.04.5 LTS
Plex version: 1.29.1.6276 

## Expected Behavior

Episode called `4-nin wa Sorezore Uso wo Tsuku - 01` should be seen as S01E01.

## Current Behavior

The episode is seen as S01E04, and I reckon it's because of the `4` in the beginning of the title.
[The Little Lies We All Tell (2022) [tvdb-418376].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9794631/The.Little.Lies.We.All.Tell.2022.tvdb-418376.scanner.log)
[The Little Lies We All Tell (2022) [tvdb-418376].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9794633/The.Little.Lies.We.All.Tell.2022.tvdb-418376.filelist.log)

## Steps to Reproduce

1. Add a folder as `The Little Lies We All Tell (2022) [tvdb-418376]` (or something else, as long as the tvdb matches).
2. Add `4-nin wa Sorezore Uso wo Tsuku - 01`  file.
3. Let ASS do its thing.
4. See the first episode as the fourth.

## Additional information

N/A

**Comment by ZeroQI** [comment]
The Little Lies We All Tell (2022) [tvdb-418376]/Season 01/4-nin wa Sorezore Uso wo Tsuku - 01.mkv

Working as designed. These are the supported naming since the series name include a number:
- The Little Lies We All Tell (2022) [tvdb-418376]/Season 01/The Little Lies We All Tell (2022) 01.mkv
- 4-nin wa Sorezore Uso wo Tsuku [tvdb-418376]/Season 01/4-nin wa Sorezore Uso wo Tsuku - 01.mkv

Also, when the episode numbers will be 3 or more, the 4 in the title will be skipped automatically

**Comment by DJScias** [comment]
Changed the folder name to `4-nin wa Sorezore Uso wo Tsuku [tvdb-418376]` and it was resolved.

I guess I just figured since the TVDB was manually added that the scanner would know both the english and romanji name for episode numbering through ID. No problem though if it's intended.

**Comment by ZeroQI** [comment]
I wouldn't say it's intended per say, but the scanner reduce complexity by removing the series name from the folder name first.
Because they differ, it remove the hyphen as separator and use the first digit it encounters

Tvdb ID is mainly for the agent, the scanner would only read meta from the scanner for tvdv2-5.
There is another skip when it find the same number too often in the filenames but you need 3 files minimum for it to trigger...
