### ISSUE TITLE
tvdb4.mapping, but for anidb (Custom Arcs for anidb)

### ISSUE THREAD

**Issue by Dalarialus** [ZeroQI/Absolute-Series-Scanner#434]
**Is your feature request related to a problem? Please describe.**
Recently, tvdb merged all of the Pokemon shows together and combined their series in a strange way. I used to be able to separate Pokemon Journeys into it's own show, with Journeys, Master Journeys, Ultimate Journeys as separate seasons within that show. I can no longer do this, and anidb lists all of Journeys as a single show with no defined series/arcs.

**Describe the solution you'd like**
I'd like to be able to use a tvdb4.mapping like file for anidb shows to define custom arcs and have Plex display them as seasons.

**Describe alternatives you've considered**
I can't think of any alternatives that would provide the desired result.

**Additional context**
N/A

**Comment by ZeroQI** [comment]
AniDB is for single seasons only so an AniDB mapping makes no sense to me...

Can you not use tvdb absolute numbering and use tvdb4 mode to make your own custom seasons by dropping the absolutely numbered episodes to seasons folders for each arc ? You could also add to a local tvdb4 mapping file or better submit it here https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml a mapping ?

Since you did not give the mapping or described Pokemon shows and how they merge, i cannot confirm there is a need for such development, i cannot see articulated why we can't use tvdb mapping to achieve this particularily...

You could create A 'Pokemon Journeys' collection and put seperate AniDB numbered show together inside (Journeys, Master Journeys, Ultimate Journeys)

**Comment by Dalarialus** [comment]
If I used tvdb4 mapping, would that not merge Journeys with the rest of Pokemon into a single show (As I'd have folders called `Pokemon [tvdb4-76703]` and `Pokemon Journeys [tvdb4-76703]`)?

I'd rather not create a separate collection for Journeys, as I already have a collection for Pokemon, which I'd like Journeys to exist within.

TVDB maps Journeys as S19 on the "Aired Order", and as S23-S25 on the "International Order" (This apparently shows as "Regional Order" on what TVDB are referring to as "API-connected systems"). AniDB lists the entirety of Journeys as a single show.

I guess what I'm after is for Journeys to appear as it's own show, separate from the rest of Pokemon (because it's a different setting, and used to exist on TVDB as a separate show), split into three seasons, though because of how TVDB maps it, I have no idea how I'd achieve that (If this is doable with advanced modes naming, I apologise for my ignorance >.<).

**Comment by ZeroQI** [comment]
Plex would group series with the same unique ID but for Hama it is more
than the forced ID alone

Since anidb separates the seasons into shows and tvdb group them and you
want them grouped tvdb is the logical answer. Tvdb4 allow to use custom
seasons but the episodes need to be in the tvdb absolute numbering format.
No need to pass through mapping file if you put the absolutely numbered
episodes into seasons yourself.

Collection: Pokemon
- Series: Pokemon [tvdb-76703]
  o Folder: Season 1...
- Series: Pokemon Journeys [tvdb4-76703]
  o Folder: Season 1 Journeys
    - File: Episode 1087 Enter Pikachu!.ext
  o Folder: Season 2 Master Journeys
    - File: Episode 1135 To train, or not to train!.ext
    - File: Episode 1176 Shodown at the gates of warp!
  o Folder: Season 3 Ultimate Journeys
- File: Episode 1177?

Season 3 is empty in TheTVDB so things could change but that should solve
your custom request.
