### ISSUE TITLE
Specials (NCOP/NCED) mapping is bugged if anidb2 forced ids are used for series and there is more than 1 Season

### ISSUE THREAD

**Issue by plantysnake** [ZeroQI/Absolute-Series-Scanner#437]
## Platform

Operating system and version: linuxserver/plex docker, debian 11
Plex version: 1.32.3.7192

## Expected Behavior

Opening/Ending for Season 2 should be mapped as separate episodes

## Current Behavior

Opening/Ending for Season 2 are mapped as versions of Opening/Ending for Season 1.

[Kami-tachi ni Hirowareta Otoko.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11759562/Kami-tachi.ni.Hirowareta.Otoko.filelist.log)
[Kami-tachi ni Hirowareta Otoko.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11759563/Kami-tachi.ni.Hirowareta.Otoko.scanner.log)

## Steps to Reproduce

1. Use anidb2 forced ids for seasons
2. Add OP/ED for Season 1
3. Add OP/ED for Season 2
4. Scan library

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/46827461/ecfc4587-6e25-40cc-bd59-eba5e24da7ae)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/46827461/c9e70270-262f-46ce-a68b-5aec135244d3)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/46827461/234a282b-fcf1-467d-9bee-a4b7041ffa7b)

P.S. fields are empty, because this is an example to replicate the bug

**Comment by ZeroQI** [comment]
If you force anidb, you are basically forcing a tvdb I'd numbering, hence tvdb specials numbering and tvdb doesn't record beginning/endings so I guess the manual op/ed manual range assignment is off?

One would have to offset op/ed by the previous number of op/ed in prior seasons, load all those xml... 

Issue is that they are separate scanner iteration so you would need to count to keep track...

**Comment by ZeroQI** [comment]
op-ed detected ok but not the numbering due to not following ANIDB specials naming convention
since anidb2 mode map to tvdb id, and the two folders are two separate instances of the scanner run, the second series need to know it is opening 2, so working as designed. You cannot take the lazy option of using anidb2 mode to not have to find the tvdb id and do expect that magically one folder knows that the other have another opening and ending already scanned... TV-1 is not recognised as an episode numbering and neither is TV-2, and they should realistically not.

Kami-tachi ni Hirowareta Otoko/Kami-tachi ni Hirowareta Otoko TV-1 [anidb2-15400]
- Kami-tachi ni Hirowareta Otoko TV-1 NCED.mkv
- Kami-tachi ni Hirowareta Otoko TV-1 NCOP.mkv
Kami-tachi ni Hirowareta Otoko/Kami-tachi ni Hirowareta Otoko TV-2 [anidb2-16364]/
- Kami-tachi ni Hirowareta Otoko TV-2 NCED**2**_.mkv
- Kami-tachi ni Hirowareta Otoko TV-2 NCOP**2**.mkv
