### ISSUE TITLE
Using Season tags does not work `[anidb-1234-s1]`

### ISSUE THREAD

**Issue by efalsken** [ZeroQI/Absolute-Series-Scanner#456]
I think we spoke about this previously, and I've tried a bunch of different ways. I can't get it to recognize season-override at all. My intention is to use this to fix `S02E01` style episode numbering because I use `anidb` series-season style library. (no grouping folders involved in this repro)

```
Kingdom - TV1 (2012) [anidb-8791]
   Kingdom S01E01.mkv
Kingdom - TV2 (2013) [anidb-9672-s1]
   Kingdom S02E08.mkv
Kingdom - TV3 (2000) [anidb-15259-s-2]
    Kingdom S03E14.mkv
Kingdom - TV4 (2022) [anidb-16912]
    Kingdom S04E14.mkv
```

In this case, each folder is recognized as a different series (correctly) but when listing the episodes, they still show all of the episodes as either Season 2/3/4. The intention was to map all of the episodes to each series' "Season 1" so that metadata can be downloaded from anidb for all of the episodes.

**Further** using a season-negative-offset value seems to prevent the scanner from finding the series id: `[anidb-15259-s-2]`. Using "fix match" and removing the `-s-2` from the name (`[anidb-15259-s-2]`) and it matches perfectly.

**Note** Episode-offset notation does seem to work properly. `[anidb-17091-e-13]` correctly causes Plex to see `[ASW] Kyoukai Senki - 15 [1080p HEVC][F8C796E0].mkv` as `S01E02`.

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/253640/2a2237e2-2ef3-4d18-b48e-eb6c523d4751)

**Comment by ZeroQI** [comment]
Anidb only has one season.
Why not follow tvdb numbering if you are going to use anidb series per season?

**Comment by efalsken** [comment]
> Anidb only has one season. Why not follow tvdb numbering if you are going to use anidb series per season?

I like Anidb id-per-season because too many anime series are non-conformant with OVA and Specials and Movies that break the normal progression of seasons. I end up using Plex collections to link them together and updating the sort so they appear in the order that makes sense even when TVDB wouldn't have linked them.

It gets even more confusing now that some series are being called "Season 2 Part 1" and "Part 2" instead of "Season 3"....

In this case, the file names sometimes have `S02` in them, but it causes the episodes to not match what shows in Anidb and they don't get titles and episode info. It might be that I should be using one of the other `anidb2` or some such mappings-type-id instead to do the same thing, but I couldn't figure out which one to use.

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/253640/73cf3bb4-d40d-4a4a-88b8-da29b85252ac)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/253640/4303783d-6eba-4594-8d4f-f096522aa43c)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/253640/e121cba0-f440-4cff-98fa-8091d7cf217e)

**Comment by ZeroQI** [comment]
It comes back to selecting a numbering, anidb or tvdb, and Plex should display the selected numbering as per the selected metadata source (anidb if single season, tvdb if season 2+ exist for files)... 
- Any other metadata based system allow only anidb or tvdb and the users have to match the numbering, and I gave some flexibility here
- Anidb2 will move season and episodes so it will look identical to tvdb as if you had numbered seasons and episodes correctly... 
- anidb 3/4 mode were not coded by me and use anidb relationships to move into seasons the individual anidb series / oav but that for me is dodgy and unsupported as result will vary greatly... It is closer to what you are doing though... 
- One cannot have anidb with s03e04 type numbering as anidb is single season. Had you not assigned an anidb ID it would have assigned a tvdb ID since it uses multiple seasons...
- The series title is subtracted from the filename so "title S2/title S2 01.ext" will be season 01 (default).

I cannot understand the argumentation of anidb over tvdb... Why A over B ? Give an explanation without mentioning B

Solution 1: anidb numbering while renaming file correctly
- Kingdom - TV1 (2012) [anidb-8791]
   Kingdom E01.mkv
- Kingdom - TV2 (2013) [anidb-9672]
   Kingdom E08.mkv
- Kingdom - TV3 (2000) [anidb-15259]
    Kingdom E14.mkv
- Kingdom - TV4 (2022) [anidb-16912]
    Kingdom E14.mkv

Solution 2: anidb numbering without renaming files
- Kingdom - TV1 (2012) [anidb-8791]
   Kingdom S01E01.mkv
- Kingdom - TV2 (2013) [anidb-9672-s1]
   Kingdom S02E08.mkv
- Kingdom - TV3 (2000) [anidb-15259-s1]
    Kingdom S03E14.mkv
- Kingdom - TV4 (2022) [anidb-16912-s1]
    Kingdom S04E14.mkv

Fix negative season offset
- Need ASS scanner log showing the output

**Comment by efalsken** [comment]
Yeah. You got the reason for the numbering right on. 
- anidb is more granular and makes it MUCH easier to make sure I've collected everything. Collecting is just as much of a hobby as running this server or watching.
- anidb numbering is much easier to let me place seasons, movies, and OVAs in the correct watch order.
- If I download a series, it's often a PITA to re-number the episodes from `13` to `01` again..... At least bulk-rename can deal with removing the `S02` part. But either way (for example) it would make hosting torrents a lot harder since the file names wouldn't match the original. So I thought I had found a solution that didn't require renaming every file if I could include either an episode-offset `-e-12` or season-override `-s1` on an entire folder.

This ticket is exactly as you mention in "Solution 2". This override does not work. In the original post I included 3 different ways I had tried. None worked as intended and `Season 2/3/4` still show in the Plex UI.

```
Kingdom - TV1 (2012) [anidb-8791]           # no override needed, scans as season 1
   Kingdom S01E01.mkv
Kingdom - TV2 (2013) [anidb-9672-s1]        # absolute season number, scans as season 2
   Kingdom S02E08.mkv
Kingdom - TV3 (2000) [anidb-15259-s-2]      # season offset, scans as season 3
    Kingdom S03E14.mkv
Kingdom - TV4 (2022) [anidb-16912]          # no season override, scans as season 4
    Kingdom S04E14.mkv
```

From the readme, I assume that the season-override only supports the absolute season number and not the offset, since the offset method wasn't mentioned. I just tried it for debugging purposes.

[Kingdom - TV3 (2000) [anidb-15259-s1].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/12774194/Kingdom.-.TV3.2000.anidb-15259-s1.scanner.log)

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L872
line 0088: SOURCE_ID_OFFSET       = cic(ur'(?P<id>\d{1,7})-(?P<season>s\d{1,3})?(?P<episode>e-?\d{1,3})?')
line 0806: offset_match = SOURCE_ID_OFFSET.search(id)
could edit line 880 and the 2 following lines to always display the manual season mapping values for troubleshooting

Scanner logs should show "Manual file offset -..."
Are you sure you are using latest code for Absolute Series Scanner.py (should be 1353 lines long)

**Comment by efalsken** [comment]
I've confirmed that i was doing it wrong. it requires a 2-digit season offset. `[anidb4-5424-s01]`
