### ISSUE TITLE
Library Empty 

### ISSUE THREAD

**Issue by PandaaZillaa** [ZeroQI/Absolute-Series-Scanner#480]
It scans the intros, and detects the movies, but the Library shows Empty. I have attached the logs (I think these are the logs you need).

[Plex Media Scanner.1.log](https://github.com/ZeroQI/Hama.bundle/files/13963528/Plex.Media.Scanner.1.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/13963533/com.plexapp.agents.hama.log)

![image](https://github.com/ZeroQI/Hama.bundle/assets/140859530/2ba00dba-0734-418d-8e4c-34c464a11c2a)
![image](https://github.com/ZeroQI/Hama.bundle/assets/140859530/9c99810a-7f85-4c8f-9520-f8d2cea5588d)

**Comment by ZeroQI** [comment]
First line of the readme:

> Absolute Series Scanner (ASS):
> If all video files are showing in plex at the right season and episode number, the scanner did its job

Nothing is showing at the right season and episode number, since nothing is showing, clearly a scanner issue
- HamaMovies is a MOVIE metadata agent, so you have a movie library
- Absolute Series Scanner is a SERIES scanner, not a movie one, so it appears to me that you put the scanner python file into  Scanners/Movies/Absolute Series Scanner.py, which is NOT supported, it should be Scanners/Series/Absolute Series Scanner.py, and Use plex movie scanner for movie library (template: library root folder/movie title (year) [garbage tag to be dropped].ext)
