### ISSUE TITLE
DATE_RX not matching youtube video date

### ISSUE THREAD

**Issue by organic-rust** [ZeroQI/Absolute-Series-Scanner#497]
When dates are included in youtube video filenames in a folder with a youtube channel id, the file timestamp is being used for the season year instead of the year in the filename. Dates in my filenames are formatted yyyy-mm-dd

## Platform
Operating system and version: Debian 12
Plex version: 1.40.2.8395
Python version 3.11.2 installed on system

## Expected Behavior
Season year should be read from filename

## Current Behavior
Videos are being put into incorrect season year (due to incorrect timestamps being set by yt-dlp)

## Additional information
Replacing "\2" in the DATE_RX regular expressions with "[\-\.\/\_]" (same as first separator, the backslashes are being removed) fixed the issue for me

**Comment by ZeroQI** [comment]
/2 should repeat the same delimiter, please indicate the filename(s) impacted

**Comment by organic-rust** [comment]
[log.txt](https://github.com/user-attachments/files/16720572/log.txt)

Attached the log, maybe that will be more useful as it shows the seasons the files are being put into as well

**Comment by organic-rust** [comment]
I played around with it a little and it looks like there are some unnecessary brackets creating duplicate capture groups, and I think it also needs round brackets around the separator so that it can be referenced? I've tested the following and it seems to be working

`DATE_RX         = [ cic(ur'(?P<year>19[0-9][0-9]|20[0-3][0-9])([\-\.\/\_])(?P<month>0[1-9]|1[0-2])\2(?P<day>0[1-9]|[12][0-9]|3[01])'),                                       #2024-05-21, 2024/25/31, 2024.05.31
                    cic(ur'(?P<day>0[1-9]|[12][0-9]|3[01])([ \-\.\/\_])(?P<month>0[1-9]|1[0-2])\2(?P<year>19[0-9][0-9]|20[0-3][0-9])')]                                        #21-05-2024, 21/05/2024, 21.05.2024
`

If those are necessary, leaving them in and changing \2 to \3 also works. I'm not sure if there's a difference

**Comment by ZeroQI** [comment]
Date used is the file creation date and the regex doesn't seem to trigger a match...
DATE_RX         = [ cic(ur'(?P<year>19[0-9][0-9]|20[0-3][0-9])([\-\.\/\_])(?P<month>0[1-9]|1[0-2])\2(?P<day>0[1-9]|[12][0-9]|3[01])'),                                       #2024-05-21, 2024/25/31, 2024.05.31 
                            cic(ur'(?P<day>0[1-9]|[12][0-9]|3[01])([ \-\.\/\_])(?P<month>0[1-9]|1[0-2])\2(?P<year>19[0-9][0-9]|20[0-3][0-9])')]                                        #21-05-2024, 21/05/2024, 21.05.2024 

Am bad with regex, but they look good to me, tested on https://regex101.com/
- (?P<year>19[0-9][0-9]|20[0-3][0-9])([\-\.\/\_])(?P<month>0[1-9]|1[0-2])\2(?P<day>0[1-9]|[12][0-9]|3[01])
- 2017-02-01 Joe Goes To The Techno Parade In Paris [A3lVh05OyPQ].webm

I would like to avoid allowing different separators as it could trigger matches in weird ways

/^(?P<year>19[0-9][0-9]|20[0-3][0-9])([\-\.\/\_])(?P<month>0[1-9]|1[0-2])\2(?P<day>0[1-9]|[12][0-9]|3[01])')$/
//                                                        ^                                                     ^
//                                                         |                                                      +---- match capturing group #2
//                                                        +----------------- capturing group #2

cannot see why the separator would be capturing group 3 instead of 2...
