### ISSUE TITLE
Scanner not picking up file in directory root

### ISSUE THREAD

**Issue by Xalaxis** [ZeroQI/Absolute-Series-Scanner#54]
Hi, I was having trouble getting a file to scan and when I checked my logs I found:
>WARNING - show: '', s00e501-501, file: 'Z:\Ookami Kodomo no Ame to Yuki [anidb-8832].mkv' has show empty, report logs to dev ASAP
So I decided it probably wasn't me making a mistake and probably something more code-related going wrong :stuck_out_tongue: .

My logs are attached.
[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/450728/Logs.zip)
(I've tried to snip the files a bit so you don't have to go looking through lots and lots of backlog, let me know if you need the history though)

**Comment by ZeroQI** [comment]
Absolute Series Scanner is a series scanner, that tries to avoid renaming files and recognize movies if:
- title is the same as the folder
- tile ends with " - Complete Movie.ext"
- there is a single file in the folder

The forcing of ids is explicit in the read-me "Forcing the series ID" section:
You can specify the guid to use the following way:
- In custom search serie name by adding " [guid_type-id_number]" at the end
- In Serie folder name by adding " [guid_type-id_number]" at the end
- In guid_type.id inside serie folder with the id in it (ex: tvdb.id file with tvdbid "114801" without double quotes in it)

Forcing IDs on the files themselves is not supported. In all fairness, i could change the code on root to support ids on files, but i need need to draw the line somewhere and since i use the filenames of all files in the same folder to find patters or duplicate ep numbers, it could cause problems if too many files were present, and you would need to convince me why i should do that when a movie folder wasn't used, and when "  - Complete Movie" isn't present in the title...

The message "has show empty, report logs to dev ASAP" is a catchall when the show is empty, which i should remove since all persons ever reporting so far had misnamed files in root
WARNING - show: '', s00e501-501, file: 'Z:\Ookami Kodomo no Ame to Yuki [anidb-8832].mkv' has show empty, report logs to dev ASAP
"" s0000e501 "Ookami Kodomo no Ame to Yuki [anidb-8832].mkv"

The proper naming convention would be: 
- Ookami Kodomo no Ame to Yuki [anidb-8832]/Ookami Kodomo no Ame to Yuki.mkv
- Ookami Kodomo no Ame to Yuki/Ookami Kodomo no Ame to Yuki.mkv
- Ookami Kodomo no Ame to Yuki  - Complete Movie.mkv

I will close this but feel free to reply if you disagree or ahave a genuine use case for the way you named the file.

**Comment by Xalaxis** [comment]
Ah, gotcha.  I'll rename the file and give it a shot.  Is the movie detection logic made clear in the documentation or have I missed it somehow?

**Comment by Xalaxis** [comment]
I can confirm the changes you suggested fix the detection

**Comment by ZeroQI** [comment]
Of course it does i wrote the bloody thing :+1: 
To your defense, the movie is maybe in the wrong section but was notheless there:
Series
Specials chars handling ("CØDE：BREAKER") and files starting with dots (".Hack")
Movie files in Series libraries accepted if they are in a folder with the same name (or 01|ep 01|s01e01, or " - Complete Movie" at the end)
