### ISSUE TITLE
Local subtitle not scanned with language code.

### ISSUE THREAD

**Issue by joshuaavalon** [ZeroQI/Absolute-Series-Scanner#79]
For example, `a.mp4` and `a.ass` will show in the web where the the subtitle is unkown. If I rename it to `a.zh.ass`, the is no subtitle anymore.

**Comment by joshuaavalon** [comment]
It seems that it can be fixed by putting "local media assets" agent first

**Comment by joshuaavalon** [comment]
The workaround only words if the file name has extra information.
For example,
```
a - s01e01.mp4
a - s01e01.ass // Unkown subtitle
a - s01e02.mp4
a - s01e02.zh.ass // Not shown
a - s01e03 - tv.mp4
a - s01e03 - tv.zh.ass // Not shown (correct if work around by putting "local media assets" agent first)
```

**Comment by ZeroQI** [comment]
Scanners do not add subtitles, as they are added/managed by Plex agent "Local Media Assets (TV)".
Make sure the agent in ticked in PMS settings > Server > Agents > Shows > HamaTV > [x] Local Media Assets (TV) and before hama

I cannot see any code in thetvdb agent for subtitles not should agents really manage subtitles beyond subtitle specific agents, the one downloading needing a specific metadata id to be used won't be compatible with Hama metadata ids generated by the search() function generally...

Try to add to the agent in "contributes_to" the value ", 'com.plexapp.agents.none'" to ['com.plexapp.agents.localmedia'] at the very bottom of the code __init__.py:
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py

If it solves, i will add the code to HAMA source.
If not all issues are fixed by putting "local media assets" agent ticked and first then do report the issue here: https://github.com/plexinc-agents/LocalMedia.bundle/issues

Two pages show support for subtitles local files:
- https://github.com/plexinc-agents/LocalMedia.bundle/blob/master/Contents/Code/localmedia.py
- https://github.com/plexinc-agents/LocalMedia.bundle/blob/master/Contents/Code/subtitlehelpers.py

**Comment by joshuaavalon** [comment]
@ZeroQI OK, it seems that the issue on plex server. I edit the collection and save again seems to fix the issue, I have tried to update it many times before that but it has no effect. Werid...

**Comment by ZeroQI** [comment]
Thanks for letting me know, weird indeed
